import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import Layout from "@/components/layout/Layout";
import RouteSchema from "@/components/RouteSchema";
import { getHreflangAlternates } from "@/lib/seo/discoveryTags";
import { industryBySlug, industries } from "./copy";

export function generateStaticParams(){return industries.map(i=>({slug:i.slug}));}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{
 const i=industryBySlug[(await params).slug]??industries[0];
 return {title:i.metaTitle,description:i.metaDescription,alternates:getHreflangAlternates(`/tom/${i.slug}`),openGraph:{title:i.metaTitle,description:i.metaDescription,url:`https://oarcdigital.com/tom/${i.slug}`,type:"website"},twitter:{card:"summary_large_image",title:i.metaTitle,description:i.metaDescription}};
}
export default async function IndustryPage({params}:{params:Promise<{slug:string}>}) {
 const i=industryBySlug[(await params).slug]; if(!i) notFound();
  return <Layout navTheme="dark" showMobileNav><RouteSchema type="service" path={`/tom/${i.slug}`} title={i.metaTitle} description={i.metaDescription} serviceType="Managed AI workforce" audience={[i.name]}/><main className="tom-page">
   <section className="tom-industry-hero"><div className="tom-industry-hero-art" aria-hidden="true"><span className="tom-art-status">TOM / LIVE</span><div className="tom-art-core">TOM<br/><small>OPERATOR</small></div></div><div className="tom-wrap"><p className="tom-kicker" style={{color:"#8fd6ae"}}>{i.kicker}</p><h1 className="tom-display">{i.headline}</h1><p className="tom-lead">{i.lead}</p><div className="tom-actions"><Link className="tom-button tom-button--red" href="/tom/start">Build our first mission ↗</Link><Link className="tom-button" href="/tom#force">See him work ↓</Link></div></div></section>
  <section className="tom-missed"><div className="tom-wrap"><p className="tom-kicker" style={{color:"#f5f5f3"}}>{i.missedKicker}</p><p>{i.missed}</p></div></section>
  <section className="tom-section"><div className="tom-wrap"><p className="tom-kicker">WHAT TOM HANDLES</p><h2 className="tom-display">What Tom handles</h2><p className="tom-copy">He arrives already fluent in {i.name.toLowerCase()} — then we train him on your business: your rules, your prices, your people, your exceptions. He speaks English, Maltese, Italian, German, and French, and he's on shift every hour of every day.</p><ul className="tom-list">{i.items.map(x=><li key={x}>{x}</li>)}</ul></div></section>
  <section className="tom-section tom-light"><div className="tom-wrap"><p className="tom-kicker">ONE REAL MOMENT FROM HIS SHIFT · LABELLED SIMULATION</p><h2 className="tom-display">One real moment from his shift.</h2><div className="tom-split"><div className="tom-panel"><h3>The voice, what the customer hears</h3><div className="tom-log">{i.voice.map(x=><div key={x}>{x}</div>)}</div></div><div className="tom-panel"><h3>The work, same second, behind</h3><div className="tom-log">{i.work.map(x=><div key={x}>{x}</div>)}</div></div></div><p className="tom-kicker" style={{marginTop:"1rem"}}>Labelled simulation — the demo we run on YOUR business during the first visit.</p></div></section>
   <section className="tom-section"><div className="tom-wrap"><p className="tom-kicker">WHAT HE DID BEHIND THE SCENES</p><h2 className="tom-display">{i.behindHeadline}</h2><p className="tom-copy">{i.behind}</p><div className="tom-measurement" role="img" aria-label={`Measurement visualization for ${i.name}`}><svg viewBox="0 0 800 288" preserveAspectRatio="none"><path d="M0 242 C95 236 125 226 198 232 S310 211 370 214 S504 188 568 174 S690 133 800 92" fill="none" stroke="#777" strokeDasharray="8 8" strokeWidth="3"/><path d="M0 262 C90 260 116 246 190 250 S304 236 368 226 S478 188 548 166 S690 86 800 38" fill="none" stroke="#c8102e" strokeWidth="6"/></svg></div></div></section>
   <section className="tom-section tom-light"><div className="tom-wrap"><p className="tom-kicker">HOW HE HELPS YOUR STAFF</p><h2 className="tom-display">{i.staffHeadline}</h2><p className="tom-copy">{i.staff}</p><p className="tom-copy" style={{marginTop:"2rem"}}>And he works both ways: he briefs your people, chases the internal tasks that slip, and answers your new hire's "how do we do this here?" — because he remembers everything, even when people move on.</p><div className="tom-staff-visual" aria-hidden="true"><span>STAFF BRIEF / SENT BY TOM</span><strong>Your team starts with the right context, not another inbox.</strong><small>WORKFLOW · BRIEFING · FOLLOW-UP · MEMORY</small></div></div></section>
  <section className="tom-section"><div className="tom-wrap"><p className="tom-kicker">WHAT ALWAYS STAYS WITH YOUR PEOPLE</p><h2 className="tom-display">{i.humanHeadline}</h2><p className="tom-copy">{i.humanLead}</p><ul className="tom-list">{i.humans.map(x=><li key={x}>{x}</li>)}</ul></div></section>
  <section className="tom-section tom-force"><div className="tom-wrap"><p className="tom-kicker" style={{color:"#8fd6ae"}}>{i.agentsKicker}</p><h2 className="tom-display">{i.agentsHeadline}</h2><div className="tom-card-grid">{i.agents.map(a=><article className="tom-card" key={a.name}><strong>AGENT / ACTIVE</strong><h3>{a.name}</h3><p>{a.body}</p></article>)}</div></div></section>
  <section className="tom-section"><div className="tom-wrap"><p className="tom-kicker">{i.proofKicker}</p><p className="tom-copy">{i.proof}</p><p className="tom-display" style={{fontSize:"clamp(2.5rem,5vw,5.5rem)",margin:"3rem 0"}}>{i.punch}</p><h2 className="tom-display">{i.closeHeadline}</h2><p className="tom-lead">{i.closeLead}</p><div className="tom-actions"><Link className="tom-button tom-button--red" href="/tom/start">Start with one problem ↗</Link><Link className="tom-button" href="/tom">{i.secondaryCta} ↓</Link></div></div></section>
  <section className="tom-cta"><div className="tom-wrap"><nav aria-label="Tom supporting links" className="tom-actions">{i.internalLinks.map(link=><Link className="tom-button" href={link.href} key={link.href}>{link.label}</Link>)}</nav></div></section>
 </main></Layout>;
}