"use client";

import Link from "next/link";
import { useState } from "react";
import { industries } from "./copy";

const promise = [
  "He talks to your customers — like the best you've ever hired.",
  "He does the work behind, the same second — sales, bookings, invoices, marketing.",
  "He talks to your staff too — chases the schedule, confirms the job, makes sure everything decided gets done.",
  "He watches the business — competitors, quiet days, unpaid money — and calls you every morning with what to do next.",
  "He never forgets anyone. He never leaves. Every month, he's better than the last.",
  "Our team builds him around your business — in person, in Malta — and runs him for you.",
];
const specialists = [
  ["Sales agent","Calls every new lead in seconds — while your competitor's is still sitting in an inbox. Qualifies naturally, sends the quote DURING the call, then follows up seven times without ever sounding like the seventh time."],
  ["Operations agent","Runs the day — schedules, jobs, deliveries, documents. Confirms Saturday's staffing with your manager, chases the supplier, reminds your technician about the change. Everything decided actually gets done."],
  ["Marketing agent","Asks every happy customer for the review — and gets it. Turns the questions customers really ask into your content and offers. Growth as a side effect of operating."],
  ["Vision & information agent","Reads the photo, the damaged delivery, the site conditions, the contract — understands what it's looking at, and acts. When showing beats telling, it sends the video walkthrough."],
];
const faqs = [
  ["Will my customers know it's AI?","He never pretends to be human — if anyone asks, he says so, plainly. Here's what actually happens: within ten seconds, callers stop caring. They got answered instantly, in their language, by someone who knew their name and solved their problem. That's all a customer ever wanted."],
  ["What happens when he doesn't know or something goes wrong?","He says so and hands over — to your chosen person, instantly, with the full story attached. Silence and guessing are not allowed. And every conversation he escalates makes him better at the next one."],
  ["How much work is this for me and my team?","Almost none — that's the point. Our team comes to you, maps the business, connects the tools, builds him, tests the first mission. Your team changes zero habits on day one. You approve decisions; we do everything else."],
  ["Do I lose my phone number or my systems?","No. He works inside what you already have — your number, your WhatsApp, your calendar, your CRM, your invoicing. Nothing gets replaced. It finally gets used properly."],
  ["What happens to my data?","It stays yours — every customer record, every conversation, every lesson he learns about your business. Handled to EU standards, owned by you, forever. If we ever part ways, the knowledge is yours, not ours."],
  ["What does he cost?","Less than your cheapest hire — for a workforce that never resigns, never calls in sick, and gets better every month instead of asking for a raise. Exact numbers at the first visit, sized to your business."],
];

function Orbit() {
  return <div className="tom-orbit" aria-label="Tom coordinating specialist agents">
    <span className="tom-agent">SALES / LIVE</span><span className="tom-agent">OPS / READY</span><span className="tom-agent">VISION / READING</span><span className="tom-agent">MARKETING / MOVING</span><span className="tom-agent">MEMORY / ON</span>
    <div className="tom-core">TOM<br/><small>OPERATOR</small></div>
  </div>;
}

function HeroFlow() {
  return <div className="tom-hero-flow" aria-label="How Tom works">
    <div><strong>01</strong><span>YOU TALK TO TOM</span><small>One calm front door for every customer.</small></div>
    <div><strong>02</strong><span>THE FORCE MOVES</span><small>Specialists execute the work in the same second.</small></div>
    <div><strong>03</strong><span>YOUR TEAM KNOWS</span><small>People get the brief, the decision, and the next move.</small></div>
  </div>;
}

export default function TomExperience() {
  const [scene, setScene] = useState(0);
  const scenes = [
    ["00:12 · HOSPITALITY — A guest calls late.","Answered in the guest's language, request handled, booking updated — and a note left for the morning team so nobody walks in blind."],
    ["03:10 · LOGISTICS — A delivery hits a problem.","He finds everyone affected, calls the clearance agent, updates six clients, and tells the right person exactly what needs to happen — before anyone wakes up."],
    ["08:00 · EVERY BUSINESS — Your phone rings. It's him.","Two minutes: what he handled overnight, what needs your decision, the opportunity he spotted, the experiment he wants to run. You say yes or no. He goes to work."],
    ["09:12 · HOME SERVICES — A quote went quiet.","The customer never replied. He calls, answers the hesitation, books the job — the follow-up that wins half the lost work."],
    ["14:20 · REAL ESTATE — An important date approaches.","He notices the lease renewal coming, preps the conversation, reminds the team early — the relationship saved before it needed saving."],
    ["22:40 · SALES — A lead arrives at night.","Answered in seconds, understood, qualified, next step prepared — while every competitor sleeps on it until Monday."],
  ];
  return <div className="tom-page">
    <section className="tom-hero"><video className="tom-hero-video" autoPlay muted loop playsInline poster="/media/hero/hero-customers-poster-v2.jpg" aria-hidden="true"><source src="/media/hero/hero-customers-v2.mp4" type="video/mp4"/></video><div className="tom-wrap tom-hero-grid"><div><p className="tom-kicker" style={{color:"#8fd6ae"}}>TOM · OARC DIGITAL</p><h1 className="tom-display"><span>You will have</span><span>one <em className="tom-italic">person.</em></span></h1><p className="tom-lead">He talks to your customers like the best you've ever hired — and while he talks, the work is already done.</p><div className="tom-actions"><a className="tom-button" href="#shift">See him work <span>↓</span></a><Link className="tom-button tom-button--red" href="/tom/start">Build our first mission <span>↗</span></Link></div><HeroFlow/></div><Orbit/></div></section>
    <section className="tom-promise"><div className="tom-wrap"><blockquote>{promise.map((line,i)=><p key={i}>{line}</p>)}</blockquote><p className="tom-support">One AI operator. An entire department behind him.</p></div></section>
    <section className="tom-section tom-light"><div className="tom-wrap"><p className="tom-kicker">FIRST — HEAR HIM</p><h2 className="tom-display">A voice so human, your customers will ask for him by name.</h2><p className="tom-copy">Not a robot reading a script. He pauses when he should, handles interruptions, changes tone with the moment — and switches between English, Maltese, Italian, German, and French mid-sentence if the caller does.</p><div className="tom-card-grid">{[["His own desk in your company","His own number. His own email. His own WhatsApp. Customers save his contact; staff message him like a colleague. A full presence in your business — not a widget on your website."],["He sounds like your best day","We train him on your best person — how they upsell, how they calm an angry customer, when they push and when they wait. Every caller gets your top performer. Every single time."],["He never has a bad shift","2am, Sunday, three calls at once, the fifth rude caller in a row — call two hundred sounds exactly like call one. Warm. Sharp. Yours."],["Customers hang up happy","They don't think “interesting technology.” They think “excellent service — I'll call back.” That feeling is the product."]].map(([t,b], index)=><article className="tom-card" key={t}><strong>VOICE / 0{index+1}</strong><h3>{t}</h3><p>{b}</p></article>)}</div></div></section>
    <section className="tom-section"><div className="tom-wrap"><p className="tom-kicker">HE DOESN'T JUST HEAR — HE UNDERSTANDS</p><h2 className="tom-display">He knows what the customer means. And what your business needs.</h2><p className="tom-copy">Understanding is the difference between answering and operating:</p><div className="tom-card-grid">{[["01","A caller hesitates at the price. He hears it — and offers the option that fits, not a discount that bleeds you."],["02","A customer sends a photo of the leaking pipe. He reads it, prices the likely job, and books the visit — from one image."],["03","A regular says “the usual, Friday.” He knows exactly what that means — because he remembers every order they've ever made."]].map(([n,t])=><article className="tom-card" key={n}><strong>{n}</strong><p>{t}</p></article>)}</div><p className="tom-display" style={{fontSize:"clamp(2rem,4vw,4rem)",marginTop:"5rem"}}>One operator who understands both sides of every conversation — the customer's, and yours.</p></div></section>
    <section className="tom-section tom-force" id="force"><div className="tom-wrap"><p className="tom-kicker" style={{color:"#8fd6ae"}}>ONE FACE. AN ENTIRE FORCE BEHIND HIM.</p><h2 className="tom-display">You talk to one. An army works behind him.</h2><p className="tom-copy">While he's still on the call, the force is already moving — one agent books, one chases the invoice, one preps the promotion, one updates the diary, one watches your competitors, one researches your next move. All at once. All reporting to him.</p><div className="tom-card-grid">{specialists.map(([t,b])=><article className="tom-card" key={t}><strong>AGENT / ACTIVE</strong><h3>{t}</h3><p>{b}</p></article>)}</div><p className="tom-display" style={{fontSize:"clamp(2.5rem,5vw,5.5rem)",marginTop:"5rem"}}>One colleague's simplicity. A department's output.</p></div></section>
    <section className="tom-section tom-light"><div className="tom-wrap"><p className="tom-kicker">HOW IT WORKS</p><h2 className="tom-display">He does not just answer. He finishes the job.</h2><div className="tom-split"><div className="tom-panel"><h3>The voice — what the customer hears</h3><div className="tom-log"><div>22:41 — Incoming call, +49 ··· (German)</div><div>“Guten Abend! Ein Tisch für vier, Freitag?”</div><div>“Freitag 20:00 — sehr gerne. Fensterplatz wie immer, Herr Weber?”</div><div>“Bestätigung ist auf Ihrem Handy. Bis Freitag!”</div></div></div><div className="tom-panel"><h3>The work — same second, behind</h3><div className="tom-log"><div>CRM ▸ caller matched: Weber, K. — 6 visits</div><div>CALENDAR ▸ Fri 20:00 · table 12 — CONFIRMED</div><div>SMS ▸ confirmation sent (DE)</div><div>FOLLOW-UP ▸ Tuesday no-show queued for rebook call</div></div></div></div><p className="tom-kicker" style={{marginTop:"1rem"}}>LABELLED SIMULATION — this is the demo we run on YOUR business during the first visit.</p></div></section>
    <section className="tom-section tom-day" id="shift"><div className="tom-wrap"><p className="tom-kicker">A DAY WITH TOM</p><h2 className="tom-display">See what happens while you're busy running the business.</h2><p className="tom-copy">Six moments from one shift. Tap through the clock.</p><div className="tom-chain">{scenes.map((s,i)=><button key={i} className="tom-button" onClick={()=>setScene(i)} aria-pressed={scene===i}>{s[0].split(" · ")[0]}</button>)}</div><article className="tom-card" style={{marginTop:"2rem",minHeight:"14rem"}}><strong>{scenes[scene][0]}</strong><h3>{scenes[scene][1]}</h3></article></div></section>
    <section className="tom-section tom-light"><div className="tom-wrap"><p className="tom-kicker">HE DOESN'T WAIT FOR ORDERS</p><h2 className="tom-display">He watches your business the way you would — if you had the time.</h2><p className="tom-copy">This is where he stops being support and becomes a strategist on payroll.</p><div className="tom-card-grid">{[["He watches your money","The unpaid invoice from March — chased. The quote from Tuesday — followed. The empty Tuesday nights — filled with win-back calls to customers you'd forgotten. Money found and money saved, unprompted."],["He watches your competitors","Their prices, their offers, their reviews, their moves — tracked every day, not once a year. “They dropped weekend rates 12% — here's our counter. Approve?” You never find out from a customer again."],["He tells you what your business needs","Not reports — directives. “Your margin leaks here. This segment is worth three times your focus. Stop selling that; double this.” Built from everything he sees that you can't."],["He runs the experiments","Proposes the offer, runs the test, measures honestly, keeps what works, kills what doesn't. A continuous stream of tested growth — you approve, he executes."]].map(([t,b])=><article className="tom-card" key={t}><strong>BRAIN / WATCHING</strong><h3>{t}</h3><p>{b}</p></article>)}</div></div></section>
    <section className="tom-section tom-light"><div className="tom-wrap"><p className="tom-kicker">THE CONNECTED BUSINESS LOOP</p><h2 className="tom-display">Sales, operations, marketing — one intelligence, zero dropped batons.</h2><p className="tom-copy">The lead he captures becomes the quote he sends, the job he schedules, the review he collects, and the next customer he brings in. Most businesses lose money in the gaps between departments. He has no gaps — because he IS every department.</p><div className="tom-chain">{["New lead","Conversation","Quote","Follow-up","Scheduled job","Completed work","Review","New opportunity"].map((x,i)=><span key={x}>{x}{i<7&&<i> →</i>}</span>)}</div></div></section>
    <section className="tom-section tom-light"><div className="tom-wrap"><p className="tom-kicker">HUMAN CONTROL AND TRUST</p><h2 className="tom-display">Powerful enough to run your day. Clear enough to bet your name on.</h2><ul className="tom-list"><li>You decide what he can do — his permissions are your rules, not ours.</li><li>Big decisions wait for your yes. Always.</li><li>Sensitive moments go straight to a person, with the full story attached.</li><li>Every action he takes is visible — what, when, and why.</li><li>Your business rules are built in, not hoped for.</li><li>OARC watches him, tunes him, and improves him — every month, that's our job.</li><li>Everything he learns about your business belongs to you. Forever.</li></ul><p className="tom-copy" style={{marginTop:"3rem"}}>This is how Tom serves healthcare, finance, legal, and government — without cutting a single corner.</p></div></section>
    <section className="tom-section"><div className="tom-wrap"><p className="tom-kicker">PROOF</p><h2 className="tom-display">Built for real work, not a software demo.</h2><p className="tom-copy">Everything on this page is real OARC work, real client media, or a clearly labelled simulation. As deployments go live, verified stories and before-and-after workflows land here — with evidence, never invented numbers.</p><p className="tom-copy" style={{marginTop:"2rem"}}>The category is already proven at billion-dollar scale: Harvey in legal, EliseAI in real estate, Avoca in home services, Hippocratic AI in healthcare — each built on a single slice of what Tom does. We bring every slice together, in person, in Malta. First movers here aren't taking a bet. They're taking the head start.</p></div></section>
    <section className="tom-section tom-light"><div className="tom-wrap"><p className="tom-kicker">NOT A DOWNLOAD — A TEAM THAT SHOWS UP</p><h2 className="tom-display">We come to you. We build him around your business. We run him for you.</h2><div className="tom-card-grid">{["We learn how your business works: Our specialists sit in your business and watch how it actually runs — not how the org chart says it runs.","We find the work that gets missed: The calls, follow-ups, and chases that slip — the questions nobody ever asked you.","We map the conversations and tasks: Your workflows, rules, exceptions, and your best people's methods — documented, often for the first time in your company's life.","We connect the required tools: Phone, email, WhatsApp, calendar, CRM, invoicing — wired by us. Your team changes zero habits on day one.","We build the specialist agents: Your workforce, assembled around your rules, your prices, your tone, your people.","We prove the first mission: One important job, working and measured — live in weeks, not months — before anything expands.","We run him, every month: Monitoring, tuning, new missions, plain-language reporting. While your operator runs your business, we run your operator."].map((x,i)=><article className="tom-card" key={x}><strong>0{i+1}</strong><p>{x}</p></article>)}</div></div></section>
    <section className="tom-section"><div className="tom-wrap"><p className="tom-kicker">THE VALUE THAT COMPOUNDS WHILE YOU SLEEP</p><h2 className="tom-display">Your best employee resigns one day. This one gets better forever.</h2><p className="tom-copy">Every customer, every conversation, every decision, every lesson — kept, forever. Mr. Borg's window table. The client who prefers WhatsApp. The supplier who's always late. Staff leave and take everything they know — he stays, and even trains your new hires on day one.</p><div className="tom-graph"><svg viewBox="0 0 800 320" preserveAspectRatio="none"><path d="M0 260 L800 255" fill="none" stroke="#777" strokeDasharray="8 8" strokeWidth="2"/><path d="M0 270 C140 260 150 210 280 220 S420 130 510 150 S650 45 800 35" fill="none" stroke="#c8102e" strokeWidth="5"/></svg></div><p className="tom-kicker">Month twelve is not month one repeated twelve times. This is why the first business in each industry builds a lead the late ones can't catch.</p></div></section>
    <section className="tom-section tom-light"><div className="tom-wrap"><p className="tom-kicker">THE QUESTIONS EVERY OWNER ASKS</p><h2 className="tom-display">Ask the hard ones. Everyone does.</h2><div className="tom-faq">{faqs.map(([q,a])=><details key={q}><summary>{q}</summary><p>{a}</p></details>)}</div></div></section>
    <section className="tom-section"><div className="tom-wrap"><p className="tom-kicker">INDUSTRIES</p><h2 className="tom-display">He arrives already fluent in your world.</h2><p className="tom-copy">Pre-trained on your industry before day one. Trained on YOUR business before his first call. Open your page:</p><div className="tom-list">{industries.map((i,n)=><Link className="tom-industry-link" href={`/tom/${i.slug}`} key={i.slug}><div><span>0{n+1}</span> {i.name} <b>↗</b></div></Link>)}</div></div></section>
    <section className="tom-section tom-light"><div className="tom-wrap"><p className="tom-kicker">PUT HIM NEXT TO EVERYTHING ELSE</p><h2 className="tom-display">A managed AI workforce. One relationship. One fee.</h2><p className="tom-copy">Less than your cheapest hire. We build the first mission, connect it to your business, and keep improving him as your business changes. He never resigns, never calls in sick, never asks for a raise — and everything he learns stays yours.</p><div className="tom-card-grid">{[["Tom","Answers every call, 5 languages · Does the work during the call · Chases quotes, invoices, no-shows · Coordinates your staff · Calls you each morning with a plan · Watches competitors daily · Remembers every customer forever · Improves every month, included"],["New hire","One shift, one language · Later, if remembered · When told · Is your staff · No · No · Leaves with the knowledge · Wants a raise"],["Answering service / AI chatbot","Reads a script · Types only · No hands · No · No · Never · Thin memory · Same forever"],["Agency","Doesn't answer phones · Sends you a report · Extra retainer · No · Quarterly review · Quarterly, maybe · Their notes, not yours · New scope, new invoice"]].map(([t,b])=><article className="tom-card" key={t}><strong>{t}</strong><p>{b}</p></article>)}</div></div></section>
    <section className="tom-cta"><div className="tom-wrap"><p className="tom-kicker" style={{color:"#8fd6ae"}}>A MANAGED AI WORKFORCE. ONE RELATIONSHIP. ONE FEE.</p><h2 className="tom-display">Give him one important job.</h2><p className="tom-lead">Tell us the task that takes too much time, gets missed too often, or keeps your team tied to the phone. We'll show you where he takes over. In five years, every business in Malta will have one — the first in your industry gets the head start that never closes.</p><p className="tom-copy" style={{marginTop:"3rem"}}>And yes — he has a name. You'll meet Tom on the first visit.</p><Link className="tom-button tom-button--red" href="/tom/start">Start with one problem <span>↗</span></Link></div></section>
  </div>;
}