"use client";

import Link from "next/link";
import { useState } from "react";
import { tomBriefPages } from "./tom-v2-data";

const promise = [
  "One operator receives the customer, staff, and business work.",
  "It understands your rules, your systems, your customers, and the exceptions.",
  "It takes the permitted actions while the conversation is still happening.",
  "It records every action, follows the unfinished work, and escalates the decisions it cannot own.",
  "Your team gets completed outcomes and a clear brief — not another inbox.",
  "OARC maps, builds, monitors, and improves the operating layer around your business.",
];
const specialists = [
  ["Sales agent","Calls every new lead in seconds — while your competitor's is still sitting in an inbox. Qualifies naturally, sends the quote DURING the call, then follows up seven times without ever sounding like the seventh time."],
  ["Operations agent","Runs the day — schedules, jobs, deliveries, documents. Confirms Saturday's staffing with your manager, chases the supplier, reminds your technician about the change. Everything decided actually gets done."],
  ["Marketing agent","Asks every happy customer for the review — and gets it. Turns the questions customers really ask into your content and offers. Growth as a side effect of operating."],
  ["Vision & information agent","Reads the photo, the damaged delivery, the site conditions, the contract — understands what it's looking at, and acts. When showing beats telling, it sends the video walkthrough."],
];
const faqs = [
  ["Will my customers know it's AI?","The operator never pretends to be human — if anyone asks, it says so, plainly. Here's what actually happens: within ten seconds, callers stop caring. They got answered instantly, in their language, by a system that knew their name and solved their problem. That's all a customer ever wanted."],
  ["What happens when the system doesn't know or something goes wrong?","It says so and hands over — to your chosen person, instantly, with the full story attached. Silence and guessing are not allowed. And every conversation it escalates makes the operating model better at the next one."],
  ["How much work is this for me and my team?","Almost none — that's the point. Our team comes to you, maps the business, connects the tools, builds the operator, tests the first mission. Your team changes zero habits on day one. You approve decisions; we do everything else."],
  ["Do I lose my phone number or my systems?","No. The system works inside what you already have — your number, your WhatsApp, your calendar, your CRM, your invoicing. Nothing gets replaced. It finally gets used properly."],
  ["What happens to my data?","It stays yours — every customer record, every conversation, every lesson the system learns about your business. Handled to EU standards, owned by you, forever. If we ever part ways, the knowledge is yours, not ours."],
  ["What does it cost?","Less than your cheapest hire — for a workforce that never resigns, never calls in sick, and gets better every month instead of asking for a raise. Exact numbers at the first visit, sized to your business."],
];

function Orbit() {
  return <div className="tom-orbit" aria-label="OARC coordinating specialist agents">
    <span className="tom-agent">SALES / LIVE</span><span className="tom-agent">OPS / READY</span><span className="tom-agent">VISION / READING</span><span className="tom-agent">MARKETING / MOVING</span><span className="tom-agent">MEMORY / ON</span>
    <div className="tom-core">OARC<br/><small>OPERATOR SYSTEM</small></div>
  </div>;
}

function HeroFlow() {
  return <div className="tom-hero-flow" aria-label="How OARC works">
    <div><strong>01</strong><span>WORK ARRIVES</span><small>Voice, WhatsApp, forms, email, or staff requests.</small></div>
    <div><strong>02</strong><span>THE SYSTEM ACTS</span><small>Rules, tools, permissions, updates, and follow-up.</small></div>
    <div><strong>03</strong><span>PEOPLE STAY IN CONTROL</span><small>Completed work, an audit trail, and only the decisions that need you.</small></div>
  </div>;
}

export default function TomExperience() {
  const [scene, setScene] = useState(0);
  const scenes = [
    ["00:12 · HOSPITALITY — A guest calls late.","Answered in the guest's language, request handled, booking updated — and a note left for the morning team so nobody walks in blind."],
    ["03:10 · LOGISTICS — A delivery hits a problem.","The system finds everyone affected, calls the clearance agent, updates six clients, and tells the right person exactly what needs to happen — before anyone wakes up."],
    ["08:00 · EVERY BUSINESS — Your phone rings. It's the operator.","Two minutes: what the system handled overnight, what needs your decision, the opportunity it spotted, the experiment it wants to run. You say yes or no. It goes to work."],
    ["09:12 · HOME SERVICES — A quote went quiet.","The customer never replied. The operator calls, answers the hesitation, books the job — the follow-up that wins half the lost work."],
    ["14:20 · REAL ESTATE — An important date approaches.","The system notices the lease renewal coming, preps the conversation, reminds the team early — the relationship saved before it needed saving."],
    ["22:40 · SALES — A lead arrives at night.","Answered in seconds, understood, qualified, next step prepared — while every competitor sleeps on it until Monday."],
  ];
  return <div className="tom-page">
     <section className="tom-hero"><img className="tom-hero-still" src="/media/hero/oarc-operator-campaign-still.jpg" alt="" aria-hidden="true"/><div className="tom-wrap tom-hero-grid"><div><p className="tom-kicker" style={{color:"#8fd6ae"}}>OARC OPERATOR SYSTEM · MANAGED AI WORKFORCE</p><h1 className="tom-display"><span>The call comes in.</span><span>The <em className="tom-italic">work moves.</em></span></h1><p className="tom-lead">A managed operating layer receives the request, understands the context, acts inside your systems, and gives your team the completed outcome.</p><div className="tom-actions"><a className="tom-button" href="#shift">See the system work <span>↓</span></a><Link className="tom-button tom-button--red" href="/tom/start">Define the first workflow <span>↗</span></Link></div><HeroFlow/></div><Orbit/></div></section>
      <section className="tom-promise"><div className="tom-wrap"><blockquote>{promise.map((line,i)=><p key={i}>{line}</p>)}</blockquote><p className="tom-support">One operating layer. Every permitted action visible.</p></div></section>
      <section className="tom-campaign-scene" aria-label="The OARC Operator System campaign still life"><div className="tom-wrap tom-campaign-grid"><div className="tom-campaign-copy"><p className="tom-kicker" style={{color:"#8fd6ae"}}>THE OPERATOR SYSTEM / IN FRAME</p><h2 className="tom-display">The work is the product.</h2><p className="tom-copy">A request enters. A decision is made. The record changes. The right person receives the next move. Everything else is theatre.</p></div><div className="tom-still-life" aria-hidden="true"><div className="tom-still-life__halo"/><div className="tom-still-life__plinth"/><div className="tom-still-life__console"><span>OARC</span><b>01</b></div><div className="tom-still-life__signal"/><div className="tom-still-life__block tom-still-life__block--one"/><div className="tom-still-life__block tom-still-life__block--two"/><div className="tom-still-life__block tom-still-life__block--three"/></div></div></section>
     <section className="tom-section tom-light"><div className="tom-wrap"><p className="tom-kicker">THE FRONT DOOR / VOICE IS ONLY THE INTERFACE</p><h2 className="tom-display">Voice gets the request. Execution is the product.</h2><p className="tom-copy">The system can sound natural, but that is not the point. The point is that it understands interruptions, language, context, and business rules — then changes the record, sends the confirmation, updates the schedule, and leaves the right person with the right next move.</p><div className="tom-card-grid">{[["Receives the work","Calls, WhatsApp, forms, email, and staff requests become one operational queue — with the context attached."],["Understands the business","Your vocabulary, permissions, prices, exceptions, customer history, and escalation rules are part of the operating model."],["Acts inside the tools","CRM, calendar, booking platform, invoicing, messaging, and internal records update while the interaction is live."],["Proves what happened","Every action has a timestamp, source, result, and owner. If it cannot act safely, it says so and hands over."]].map(([t,b], index)=><article className="tom-card" key={t}><strong>SYSTEM / 0{index+1}</strong><h3>{t}</h3><p>{b}</p></article>)}</div></div></section>
     <section className="tom-section"><div className="tom-wrap"><p className="tom-kicker">THE SYSTEM DOESN'T JUST HEAR — IT UNDERSTANDS</p><h2 className="tom-display">It knows what the customer means. And what your business needs.</h2><p className="tom-copy">Understanding is the difference between answering and operating:</p><div className="tom-card-grid">{[["01","A caller hesitates at the price. The system hears it — and offers the option that fits, not a discount that bleeds you."],["02","A customer sends a photo of the leaking pipe. The system reads it, prices the likely job, and books the visit — from one image."],["03","A regular says “the usual, Friday.” The system knows exactly what that means — because it remembers every order they've ever made."]].map(([n,t])=><article className="tom-card" key={n}><strong>{n}</strong><p>{t}</p></article>)}</div><p className="tom-display" style={{fontSize:"clamp(2rem,4vw,4rem)",marginTop:"5rem"}}>One operator that understands both sides of every conversation — the customer's, and yours.</p></div></section>
     <section className="tom-section tom-force" id="force"><div className="tom-wrap"><p className="tom-kicker" style={{color:"#8fd6ae"}}>SPECIALIST EXECUTION / ONE CONTROL LAYER</p><h2 className="tom-display">One request in. The right work moves behind it.</h2><p className="tom-copy">The specialist agents are not a collection of chatbots. They are permissioned workers behind one operating layer — sales, operations, finance, marketing, information, and follow-up — each returning evidence to the same record.</p><div className="tom-card-grid">{specialists.map(([t,b])=><article className="tom-card" key={t}><strong>AGENT / ACTIVE</strong><h3>{t}</h3><p>{b}</p></article>)}</div><p className="tom-display" style={{fontSize:"clamp(2.5rem,5vw,5.5rem)",marginTop:"5rem"}}>One interface for the customer. A traceable system behind it.</p></div></section>
     <section className="tom-section tom-light"><div className="tom-wrap"><p className="tom-kicker">THE PROOF OBJECT / A COMPLETED WORKFLOW</p><h2 className="tom-display">Do not take our word for it. Watch the record change.</h2><div className="tom-split"><div className="tom-panel"><h3>INPUT / WHAT ARRIVED</h3><div className="tom-log"><div>22:41 — Incoming call · +49 ··· · German</div><div>“Ein Tisch für vier am Freitag — geht das noch?”</div><div>Context: Weber, K. · 6 visits · window table</div><div>Permission: reservation + confirmation · no refund authority</div></div></div><div className="tom-panel"><h3>OUTPUT / WHAT COMPLETED</h3><div className="tom-log"><div>22:41:08 — booking confirmed · table 12</div><div>22:41:09 — confirmation sent · German</div><div>22:41:11 — guest history + preference updated</div><div>22:41:15 — owner brief + rebooking task created</div></div></div></div><p className="tom-kicker" style={{marginTop:"1rem"}}>LABELLED SIMULATION — the same evidence-led demo is rebuilt on your tools during the first visit.</p></div></section>
    <section className="tom-section tom-day" id="shift"><div className="tom-wrap"><p className="tom-kicker">A DAY WITH TOM</p><h2 className="tom-display">See what happens while you're busy running the business.</h2><p className="tom-copy">Six moments from one shift. Tap through the clock.</p><div className="tom-chain">{scenes.map((s,i)=><button key={i} className="tom-button" onClick={()=>setScene(i)} aria-pressed={scene===i}>{s[0].split(" · ")[0]}</button>)}</div><article className="tom-card" style={{marginTop:"2rem",minHeight:"14rem"}}><strong>{scenes[scene][0]}</strong><h3>{scenes[scene][1]}</h3></article></div></section>
     <section className="tom-section tom-light"><div className="tom-wrap"><p className="tom-kicker">THE SYSTEM DOESN'T WAIT FOR ORDERS</p><h2 className="tom-display">It watches your business the way you would — if you had the time.</h2><p className="tom-copy">This is where the operator stops being support and becomes a strategist on payroll.</p><div className="tom-card-grid">{[["It watches your money","The unpaid invoice from March — chased. The quote from Tuesday — followed. The empty Tuesday nights — filled with win-back calls to customers you'd forgotten. Money found and money saved, unprompted."],["It watches your competitors","Their prices, their offers, their reviews, their moves — tracked every day, not once a year. “They dropped weekend rates 12% — here's our counter. Approve?” You never find out from a customer again."],["It tells you what your business needs","Not reports — directives. “Your margin leaks here. This segment is worth three times your focus. Stop selling that; double this.” Built from everything the system sees that you can't."],["It runs the experiments","Proposes the offer, runs the test, measures honestly, keeps what works, kills what doesn't. A continuous stream of tested growth — you approve, it executes."]].map(([t,b])=><article className="tom-card" key={t}><strong>BRAIN / WATCHING</strong><h3>{t}</h3><p>{b}</p></article>)}</div></div></section>
     <section className="tom-section tom-light"><div className="tom-wrap"><p className="tom-kicker">THE CONNECTED BUSINESS LOOP</p><h2 className="tom-display">Sales, operations, marketing — one intelligence, zero dropped batons.</h2><p className="tom-copy">The lead the system captures becomes the quote it sends, the job it schedules, the review it collects, and the next customer it brings in. Most businesses lose money in the gaps between departments. The operating layer closes them.</p><div className="tom-chain">{["New lead","Conversation","Quote","Follow-up","Scheduled job","Completed work","Review","New opportunity"].map((x,i)=><span key={x}>{x}{i<7&&<i> →</i>}</span>)}</div></div></section>
     <section className="tom-section tom-light"><div className="tom-wrap"><p className="tom-kicker">HUMAN CONTROL AND TRUST</p><h2 className="tom-display">Automation is only valuable when its limits are visible.</h2><ul className="tom-list"><li>You decide which systems and actions are in scope.</li><li>Permissions follow your rules, not a generic template.</li><li>High-impact decisions wait for a person.</li><li>Sensitive moments hand over with the full context attached.</li><li>Every action is visible — what, when, why, and with which source.</li><li>OARC monitors, tunes, and improves the system with your team.</li><li>Your records and operating knowledge stay yours.</li></ul><p className="tom-copy" style={{marginTop:"3rem"}}>That is how a workforce becomes dependable infrastructure instead of another AI promise.</p></div></section>
    <section className="tom-section"><div className="tom-wrap"><p className="tom-kicker">PROOF</p><h2 className="tom-display">Built for real work, not a software demo.</h2><p className="tom-copy">Everything on this page is real OARC work, real client media, or a clearly labelled simulation. As deployments go live, verified stories and before-and-after workflows land here — with evidence, never invented numbers.</p><p className="tom-copy" style={{marginTop:"2rem"}}>The category is already proven at billion-dollar scale: Harvey in legal, EliseAI in real estate, Avoca in home services, Hippocratic AI in healthcare — each built on a single slice of what Tom does. We bring every slice together, in person, in Malta. First movers here aren't taking a bet. They're taking the head start.</p></div></section>
     <section className="tom-section tom-light"><div className="tom-wrap"><p className="tom-kicker">NOT A DOWNLOAD — A TEAM THAT SHOWS UP</p><h2 className="tom-display">We come to you. We build the operator around your business. We run it for you.</h2><div className="tom-card-grid">{["We learn how your business works: Our specialists sit in your business and watch how it actually runs — not how the org chart says it runs.","We find the work that gets missed: The calls, follow-ups, and chases that slip — the questions nobody ever asked you.","We map the conversations and tasks: Your workflows, rules, exceptions, and your best people's methods — documented, often for the first time in your company's life.","We connect the required tools: Phone, email, WhatsApp, calendar, CRM, invoicing — wired by us. Your team changes zero habits on day one.","We build the specialist agents: Your workforce, assembled around your rules, your prices, your tone, your people.","We prove the first mission: One important job, working and measured — live in weeks, not months — before anything expands.","We run it, every month: Monitoring, tuning, new missions, plain-language reporting. While your operator runs your business, we run the operating layer."].map((x,i)=><article className="tom-card" key={x}><strong>0{i+1}</strong><p>{x}</p></article>)}</div></div></section>
     <section className="tom-section"><div className="tom-wrap"><p className="tom-kicker">THE VALUE THAT COMPOUNDS WHILE YOU SLEEP</p><h2 className="tom-display">Your best employee resigns one day. The operating layer gets better forever.</h2><p className="tom-copy">Every customer, every conversation, every decision, every lesson — kept, forever. Mr. Borg's window table. The client who prefers WhatsApp. The supplier who's always late. Staff leave and take everything they know — the operating knowledge stays, and trains your new hires on day one.</p><div className="tom-graph"><svg viewBox="0 0 800 320" preserveAspectRatio="none"><path d="M0 260 L800 255" fill="none" stroke="#777" strokeDasharray="8 8" strokeWidth="2"/><path d="M0 270 C140 260 150 210 280 220 S420 130 510 150 S650 45 800 35" fill="none" stroke="#c8102e" strokeWidth="5"/></svg></div><p className="tom-kicker">Month twelve is not month one repeated twelve times. This is why the first business in each industry builds a lead the late ones can't catch.</p></div></section>
    <section className="tom-section tom-light"><div className="tom-wrap"><p className="tom-kicker">THE QUESTIONS EVERY OWNER ASKS</p><h2 className="tom-display">Ask the hard ones. Everyone does.</h2><div className="tom-faq">{faqs.map(([q,a])=><details key={q}><summary>{q}</summary><p>{a}</p></details>)}</div></div></section>
     <section className="tom-section"><div className="tom-wrap"><p className="tom-kicker">INDUSTRIES / TEN OPERATING ROOMS</p><h2 className="tom-display">Same system. Different pressure.</h2><p className="tom-copy">Open the room that looks like your Tuesday. Each page translates the system into your vocabulary, tools, failure points, permissions, and measurable work—not a generic AI story with the industry name swapped.</p><div className="tom-list">{tomBriefPages.map((i,n)=><Link className="tom-industry-link" href={`/tom/${i.slug}`} key={i.slug}><div><span>{String(n + 1).padStart(2, "0")}</span> {i.name} <b>↗</b></div></Link>)}</div></div></section>
     <section className="tom-section tom-light"><div className="tom-wrap"><p className="tom-kicker">WHAT YOU ARE ACTUALLY BUYING</p><h2 className="tom-display">Not a chatbot. Not a hire. Not an agency report.</h2><p className="tom-copy">You are buying a managed operating layer: a system that receives work, takes approved actions, proves the result, and gets better with your business.</p><div className="tom-card-grid">{[["A new hire","A person you must train, schedule, retain, and replace."],["A chatbot","An answer surface without hands, permissions, or follow-through."],["An agency","Recommendations and reports that still leave execution with your team."],["OARC Operator","A managed workforce that acts inside your systems and returns completed work with evidence."]].map(([t,b])=><article className="tom-card" key={t}><strong>{t}</strong><p>{b}</p></article>)}</div></div></section>
     <section className="tom-cta"><div className="tom-wrap"><p className="tom-kicker" style={{color:"#8fd6ae"}}>OARC OPERATOR SYSTEM / FIRST WORKFLOW</p><h2 className="tom-display">Give the system one important job.</h2><p className="tom-lead">Tell us the task that takes too much time, gets missed too often, or keeps your team tied to the phone. We will map the inputs, permissions, actions, evidence, and handoff—then show you the first workflow working on your business.</p><p className="tom-copy" style={{marginTop:"3rem"}}>“Tom” can stay as the shorthand. The thing you buy is the operating system around the work.</p><Link className="tom-button tom-button--red" href="/tom/start">Define the first workflow <span>↗</span></Link></div></section>
  </div>;
}