"use client";
import { useState } from "react";
import Link from "next/link";
import { tomBriefPages } from "../tom-v2-data";

export default function TomStartPage() {
  const [status,setStatus] = useState<"idle"|"sending"|"success"|"error">("idle");
  async function submit(e: React.FormEvent<HTMLFormElement>) {
    e.preventDefault(); setStatus("sending");
    try { const res=await fetch("https://formspree.io/f/xlgavdlp",{method:"POST",body:new FormData(e.currentTarget),headers:{Accept:"application/json"}}); setStatus(res.ok?"success":"error"); if(res.ok)e.currentTarget.reset(); } catch { setStatus("error"); }
  }
  return <main className="tom-form-page tom-form"><div className="tom-wrap tom-form-grid"><div><p className="tom-kicker" style={{color:"#8fd6ae"}}>OARC OPERATOR SYSTEM · FIRST WORKFLOW</p><h1 className="tom-display">Show us where the work still stops.</h1><p className="tom-lead">We'll map the input, rules, systems, permitted actions, evidence, and human handoff—then show you the first workflow working on your business, in person, in Malta. No obligation. We reply within one working day.</p><Link className="tom-button" href="/tom">← Back to the system</Link></div><form onSubmit={submit}><label>Name<input name="name" required autoComplete="name"/></label><label>Business<input name="business" required autoComplete="organization"/></label><label>Phone / WhatsApp<input name="phone" required autoComplete="tel"/></label><label>Email<input name="email" type="email" required autoComplete="email"/></label><label>Industry<select name="industry" required defaultValue=""><option value="" disabled>Select your industry</option>{tomBriefPages.map(i=><option key={i.slug}>{i.name}</option>)}<option>Other</option></select></label><label>What should the system handle first?<textarea name="first_mission" required placeholder="The call, follow-up, booking, document or exception that should become completed work."/></label><label className="tom-check"><input type="checkbox" name="voice_note_consent" value="yes"/> I'm happy to send a video or voice note about the workflow.</label><label>What tools does the business already use? (phone system, CRM, calendar, invoicing…) — optional<textarea name="tools"/></label><button className="tom-button tom-button--red" type="submit" disabled={status==="sending"}>{status==="sending"?"Sending…":"Map the first workflow"} <span>↗</span></button>{status==="success"&&<p className="tom-status" role="status">Received. We'll reply within one working day.</p>}{status==="error"&&<p role="alert">Something went wrong. Email hello@oarcdigital.com</p>}<p className="tom-kicker">We reply within one working day · Or just write: hello@oarcdigital.com</p></form></div></main>;
}