"use client";
import { useState } from "react";
import Link from "next/link";
import { industries } from "../copy";

export default function TomStartPage() {
  const [status,setStatus] = useState<"idle"|"sending"|"success"|"error">("idle");
  async function submit(e: React.FormEvent<HTMLFormElement>) {
    e.preventDefault(); setStatus("sending");
    try { const res=await fetch("https://formspree.io/f/xlgavdlp",{method:"POST",body:new FormData(e.currentTarget),headers:{Accept:"application/json"}}); setStatus(res.ok?"success":"error"); if(res.ok)e.currentTarget.reset(); } catch { setStatus("error"); }
  }
  return <main className="tom-form-page tom-form"><div className="tom-wrap tom-form-grid"><div><p className="tom-kicker" style={{color:"#8fd6ae"}}>TOM · FIRST MISSION</p><h1 className="tom-display">Tell us what keeps falling through the cracks.</h1><p className="tom-lead">We'll look at the work, identify the first useful mission, and show you how he'd handle it — in person, in Malta. No obligation. We reply within one working day.</p><Link className="tom-button" href="/tom">← Back to Tom</Link></div><form onSubmit={submit}><label>Name<input name="name" required autoComplete="name"/></label><label>Business<input name="business" required autoComplete="organization"/></label><label>Phone / WhatsApp<input name="phone" required autoComplete="tel"/></label><label>Email<input name="email" type="email" required autoComplete="email"/></label><label>Industry<select name="industry" required defaultValue=""><option value="" disabled>Select your industry</option>{industries.map(i=><option key={i.slug}>{i.name}</option>)}<option>Other</option></select></label><label>What should he handle first?<textarea name="first_mission" required/></label><label className="tom-check"><input type="checkbox" name="voice_note_consent" value="yes"/> I'm happy to send a video or voice note about the work.</label><label>What tools does the business already use? (phone system, CRM, calendar, invoicing…) — optional<textarea name="tools"/></label><button className="tom-button tom-button--red" type="submit" disabled={status==="sending"}>{status==="sending"?"Sending…":"Show us the first mission"} <span>↗</span></button>{status==="success"&&<p className="tom-status" role="status">Received. We'll reply within one working day.</p>}{status==="error"&&<p role="alert">Something went wrong. Email hello@oarcdigital.com</p>}<p className="tom-kicker">We reply within one working day · Or just write: hello@oarcdigital.com</p></form></div></main>;
}