import type { EditorialService } from "@/components/services/OarcEditorialServicePage";

export const editorialServices: Record<string, EditorialService> = {
  "custom-ai-agents": {
    slug: "custom-ai-agents", eyebrow: "CUSTOM AI AGENTS",
    title: "Custom AI agents that finish the work.",
    intro: "OARC builds custom AI agents for businesses in Malta and beyond. They handle defined sales, operations, research, finance, recruiting and back-office work using your tools, your permissions and a reviewable record of every action.",
    image: "/images/services/custom-ai-agents-hero.jpg", imageAlt: "A team working with connected AI workflows", accent: "#e8ff55", accentSoft: "#f3f6c9",
    ownerTitle: "You do not need another chat window. You need fewer open loops.",
    ownerCopy: "A custom AI agent turns one defined piece of work into a dependable operating path: gather the context, follow the rule, make the permitted move, update the right system and hand over when judgment belongs with a person. The value is not more AI activity. It is work that no longer waits for somebody to remember it.",
    customerTitle: "The person waiting gets an answer with a trail.",
    customerCopy: "A prospect gets a relevant next step instead of a generic chase. A finance teammate gets the figures and sources instead of an unexplained answer. A recruiter gets a prepared shortlist instead of another pile of profiles. The experience is quicker because the work behind it is visible, not magical.",
    marquee: ["FEWER OPEN LOOPS", "COMPLETED OUTCOMES", "REVIEWABLE WORK"],
    proof: [{ value: "01", label: "defined workflow" }, { value: "↗", label: "permitted actions" }, { value: "✓", label: "reviewable evidence" }],
    capabilities: [
      { title: "Sales follow-through", copy: "Research prospects, prepare relevant outreach, qualify replies and update the CRM without pretending every lead is the same." },
      { title: "Operations that keep moving", copy: "Move information between existing systems, reconcile defined records, flag exceptions and keep the responsible person in the loop." },
      { title: "Research with receipts", copy: "Return findings with the sources, assumptions and decision context a person needs before acting on them." },
      { title: "Finance administration", copy: "Prepare repeatable checks, organise supporting documents and route exceptions without inventing a figure or approving what requires a person." },
      { title: "Recruiting preparation", copy: "Collect role-relevant evidence, organise candidate information and prepare a human reviewer to make the decision." },
      { title: "Company knowledge", copy: "Answer from the material the business approves and show where the answer came from instead of guessing beyond it." },
    ],
    steps: [
      { title: "Name the completed job", copy: "We start with one result the business can recognise: a qualified meeting booked, a record reconciled, a report prepared or a request routed." },
      { title: "Define tools and limits", copy: "We map the information the agent may use, the systems it may touch, the actions it may take and the moments that require approval." },
      { title: "Run with evidence", copy: "The working agent records the request, relevant context, action, exception and hand-off so a person can inspect what happened." },
    ],
    faqs: [
      { q: "What is a custom AI agent?", a: "It is an AI system designed around a defined business workflow. It can read approved context, use permitted tools, complete steps and show the evidence behind its work." },
      { q: "What work should we automate first?", a: "Start with work that repeats, has a recognisable outcome and currently loses time between people or systems. OARC maps the workflow before recommending a build." },
      { q: "Can an agent change records or send messages?", a: "Only where the workflow allows it. OARC defines permissions and human review points before an agent performs an action." },
      { q: "How do we know what the agent did?", a: "The workflow is designed to leave reviewable evidence: the request, relevant context, action taken and any hand-off or exception." },
      { q: "What teams use custom AI agents?", a: "Sales, operations, research, finance, recruiting and back-office teams are all suitable when the work has a clear outcome and repeatable path." },
      { q: "Does a custom AI agent replace our existing software?", a: "Not necessarily. The useful role is often to work across the tools the business already relies on, subject to the access each workflow genuinely needs." },
    ],
    related: [{ title: "AI consulting", href: "/services/ai-consulting", copy: "Find the right first workflow." }, { title: "AI employee service desk", href: "/services/ai-employee-service-desk", copy: "Give your team a better front door." }],
  },
  "conversational-commerce": {
    slug: "conversational-commerce", eyebrow: "CONVERSATIONAL COMMERCE",
    title: "Conversational commerce that starts with a question.",
    intro: "OARC creates conversational commerce and AI shopping experiences for retailers in Malta and beyond. Shoppers can search in natural language, compare suitable products, ask questions and get help from discovery through the basket and checkout.",
    image: "/images/services/conversational-commerce-hero.jpg", imageAlt: "Colourful products arranged around a conversational shopping interface", accent: "#ff6d55", accentSoft: "#ffe3d7",
    ownerTitle: "More of the right products make it into the basket.",
    ownerCopy: "Your catalogue becomes easier to explore in the words shoppers actually use. A person can describe the occasion, budget, fit or problem rather than guess your product names. The experience can surface suitable choices, explain trade-offs and support a decision instead of leaving intent stranded inside a search box.",
    customerTitle: "The shopper gets help without the hard sell.",
    customerCopy: "They can ask for a gift, a size, a material, an allergy requirement or a combination of needs. They get useful recommendations, clear reasons, product answers and guidance through the basket when they are ready to buy. They keep control of the decision.",
    marquee: ["SEARCH IN HUMAN LANGUAGE", "CHOOSE WITH CONFIDENCE", "SUPPORT THE PURCHASE"],
    proof: [{ value: "01", label: "natural-language entry" }, { value: "→", label: "guided discovery" }, { value: "□", label: "checkout support" }],
    capabilities: [
      { title: "Discovery in human language", copy: "Let a shopper describe what they need, not guess the exact product name or filter combination." },
      { title: "Recommendations with reasons", copy: "Suggest products while explaining the fit, trade-off or detail that makes each one relevant." },
      { title: "Questions answered in context", copy: "Handle product questions from the approved catalogue and point people to the detail that matters." },
      { title: "Search and recommendations", copy: "Use catalogue information and merchandising rules to connect shopper intent with products that genuinely match it." },
      { title: "Basket and checkout guidance", copy: "Help with comparison, basket questions and the next step without taking control away from the shopper." },
      { title: "Merchandising insight", copy: "Expose the questions, hesitations and combinations customers express so the retail team can improve content and merchandising decisions." },
    ],
    steps: [
      { title: "Understand the catalogue", copy: "We structure the product information, attributes, policies and merchandising rules the experience is allowed to use." },
      { title: "Design the buying conversation", copy: "We map the questions shoppers ask, the comparisons they need and the points where a recommendation must explain itself." },
      { title: "Connect discovery to purchase", copy: "The experience supports the route from search and recommendation into the existing basket, checkout and human-support journey." },
    ],
    faqs: [
      { q: "What is conversational commerce?", a: "It is a shopping experience where people can use natural language to discover products, ask questions, compare options and get basket or checkout guidance." },
      { q: "How can AI help customers find the right product?", a: "It can interpret the need a shopper describes, search approved catalogue information and explain why particular products fit that request." },
      { q: "Does it replace our product catalogue?", a: "No. It gives the catalogue a more useful front door and works from the product information and rules your business approves." },
      { q: "What does the merchant gain?", a: "A clearer path from shopper intent to product choice, plus a way to answer questions that might otherwise interrupt a purchase." },
      { q: "Can shoppers still browse normally?", a: "Yes. Conversation is an additional route into discovery and support, not a demand that every shopper changes how they buy." },
      { q: "Can it work with our existing ecommerce website?", a: "That depends on the catalogue, search, basket and checkout interfaces available. OARC maps those systems before defining what the conversational layer can safely do." },
    ],
    related: [{ title: "Custom AI agents", href: "/services/custom-ai-agents", copy: "Automate work behind the storefront." }, { title: "Web app development", href: "/services/web-apps-development", copy: "Build the product experience around it." }],
  },
  "ai-employee-service-desk": {
    slug: "ai-employee-service-desk", eyebrow: "AI EMPLOYEE SERVICE DESK",
    title: "An AI employee service desk that resolves everyday requests.",
    intro: "OARC creates AI employee service desks for organisations in Malta and beyond. Employees ask in plain language; the service desk answers from approved company knowledge, performs permitted IT, HR and finance actions, logs evidence and hands complex cases to people with context.",
    image: "/images/services/ai-employee-service-desk-hero.jpg", imageAlt: "An employee using a friendly digital service desk", accent: "#b9ead9", accentSoft: "#e2f5ef",
    ownerTitle: "Fewer avoidable tickets. Better context when a person is needed.",
    ownerCopy: "Your teams get one clear front door for everyday questions and permitted requests. The people responsible for IT, HR and finance spend less time repeating policy answers, checking status and collecting missing context. Their queue becomes more useful because the cases reaching them are the cases that need judgment.",
    customerTitle: "Employees stop wondering where to ask.",
    customerCopy: "They can ask in plain language, understand the answer and see what happens next. A straightforward request can be completed where permission allows. When a case needs a person, the hand-off carries the conversation, relevant policy and evidence instead of making the employee start the story again.",
    marquee: ["ONE PLACE TO ASK", "APPROVED ANSWERS", "CONTEXTUAL HAND-OFF"],
    proof: [{ value: "01", label: "approved knowledge" }, { value: "↗", label: "permitted actions" }, { value: "→", label: "contextual hand-off" }],
    capabilities: [
      { title: "Answers from approved knowledge", copy: "Give employees a useful answer grounded in the policies, procedures and information your organisation has chosen." },
      { title: "IT service requests", copy: "Support defined requests such as access help, software requests, ticket creation and status checks where connected systems and permissions allow." },
      { title: "HR and policy support", copy: "Explain approved leave, onboarding, benefits and workplace policies while routing personal decisions to the right people." },
      { title: "Finance questions", copy: "Guide employees through approved expense, invoice and purchasing processes without inventing policy or approving exceptions." },
      { title: "Decisions explained", copy: "Make the next step legible: what was checked, what can happen now and why a request needs review." },
      { title: "Human escalation with context", copy: "Pass complex cases to the right person with the conversation and relevant evidence attached." },
    ],
    steps: [
      { title: "Bring the approved knowledge", copy: "We identify the policies, procedures, service records and answers each employee audience is permitted to access." },
      { title: "Connect safe actions", copy: "We define which requests may be completed, which need approval and which must always go directly to a person." },
      { title: "Review every resolution", copy: "Answers, actions and escalations leave a trace so service owners can inspect quality, find knowledge gaps and improve the experience." },
    ],
    faqs: [
      { q: "What does an AI employee service desk do?", a: "It answers employee questions from approved company knowledge, performs permitted actions and routes complex cases to people with context." },
      { q: "Can an AI service desk help with IT, HR and finance requests?", a: "Yes, when each service has approved knowledge, connected workflows and explicit permissions. The boundaries are defined separately for every type of request." },
      { q: "Can it make HR or finance decisions?", a: "It can support defined, permitted actions. Decisions that require human judgment remain with the appropriate people." },
      { q: "How does it reduce avoidable tickets?", a: "It gives employees one clear place to ask everyday questions and complete straightforward requests instead of creating a ticket for each one." },
      { q: "What happens when the AI cannot answer?", a: "The service desk explains that it needs help and hands the case to a person with the relevant conversation and evidence." },
      { q: "Does it replace our existing service desk software?", a: "It can work as a conversational front door to existing knowledge and service workflows. The exact approach depends on the systems and interfaces already in place." },
    ],
    related: [{ title: "Custom AI agents", href: "/services/custom-ai-agents", copy: "Put repeatable work on a reliable path." }, { title: "AI consulting", href: "/services/ai-consulting", copy: "Choose the right first use case." }],
  },
};