// Shared builder for `public/llms-full.txt`. Imported by the generator
// (`scripts/generate-llms-full-txt.ts`) AND the audit-framework parity gate
// so both sides reference one source of truth — no drift possible.
//
// The autogenerated body is bounded by AUTOGEN markers. The Start here +
// Actions block above it is also generator-owned; other content (custom
// human-authored notes, footer signatures) is preserved by the transform.

import { SERVICE_SCHEMAS, type ServiceSchemaEntry } from "./serviceSchemaConfig";
import { PILLAR_SCHEMAS, type PillarSchemaEntry } from "./pillarSchemaConfig";
import { NAP } from "./nap";
import {
  buildSupplementalLlmsFullEntries,
  buildStartHereSection,
  START_HERE_START,
  START_HERE_END,
  curateDiscoveryText,
} from "./llmsTxtGenerator";
import { buildH360LlmsFullSection } from "./h360LlmsGenerator";

export const LLMS_FULL_PATH = "public/llms-full.txt";
export const LLMS_FULL_START = "<!-- AUTOGEN:LLMS-FULL:START -->";
export const LLMS_FULL_END = "<!-- AUTOGEN:LLMS-FULL:END -->";

function pillarCanonical(pPath: string): string {
  return pPath === "/" ? "https://oarcdigital.com/" : `https://oarcdigital.com${pPath}`;
}

function serviceCanonical(slug: string): string {
  return `https://oarcdigital.com/services/${slug}`;
}

function emitFaqs(lines: string[], faqs: { question: string; answer: string }[]) {
  if (!faqs?.length) return;
  const safeFaqs = faqs.flatMap((f) => {
    const question = curateDiscoveryText(f.question);
    const answer = curateDiscoveryText(f.answer);
    return question && answer ? [{ question, answer }] : [];
  });
  if (!safeFaqs.length) return;
  lines.push("**FAQs**", "");
  for (const f of safeFaqs) {
    lines.push(`Q: ${f.question}`);
    lines.push(`A: ${f.answer}`);
    lines.push("");
  }
}

function emitFacts(
  lines: string[],
  facts: { claim: string; source?: string }[],
) {
  if (!facts?.length) return;
  const safeFacts = facts.flatMap((f) => {
    const claim = curateDiscoveryText(f.claim);
    return claim ? [{ claim, source: f.source }] : [];
  });
  if (!safeFacts.length) return;
  lines.push("**Cite-able facts**");
  lines.push("");
  for (const f of safeFacts) {
    if (f.source) {
      lines.push(`- ${f.claim} (source: ${f.source})`);
    } else {
      lines.push(`- ${f.claim}`);
    }
  }
  lines.push("");
}

function emitFeatures(lines: string[], features: { name: string }[] | undefined) {
  if (!features?.length) return;
  const safeFeatures = features.flatMap((f) => {
    const name = curateDiscoveryText(f.name);
    return name ? [{ name }] : [];
  });
  if (!safeFeatures.length) return;
  lines.push("**Features**");
  lines.push("");
  for (const f of safeFeatures) {
    lines.push(`- ${f.name}`);
  }
  lines.push("");
}

function staticHeader(): string {
  const lines: string[] = [];
  lines.push("# OARC Digital — Full Reference for AI Answer Engines");
  lines.push("");
  lines.push(
    "> Auto-generated body between AUTOGEN markers below from `lib/seo/serviceSchemaConfig.ts` + `lib/seo/pillarSchemaConfig.ts` + `lib/seo/serviceSchemaExtras.ts` by `scripts/generate-llms-full-txt.ts`. Do not hand-edit INSIDE the markers — re-run the generator. Content OUTSIDE the markers is preserved across runs.",
  );
  lines.push("");
  lines.push(
    `Canonical NAP: ${NAP.name} | ${NAP.streetAddress}, ${NAP.addressLocality} ${NAP.postalCode}, Malta | ${NAP.phoneDisplay} | ${NAP.email}`,
  );
  lines.push("");
  lines.push(buildStartHereSection());
  lines.push("");
  lines.push("## Search support");
  lines.push("");
  lines.push(
    "- [AI-native marketing agency definition](https://oarcdigital.com/ai-native-marketing-agency) — what the term means and how the operating model works.",
    "- [Press resources](https://oarcdigital.com/press) — canonical company description, contact details, and editorial links.",
  );
  lines.push("");
  lines.push("---");
  lines.push("");
  return lines.join("\n");
}

function safeHeading(value: string, fallback: string): string {
  return curateDiscoveryText(value) ?? fallback;
}

function emitOptionalField(lines: string[], heading: string, value: string | undefined): void {
  const safe = value ? curateDiscoveryText(value) : null;
  if (!safe) return;
  lines.push(heading, safe, "");
}

// The autogenerated body — everything between (and including) the AUTOGEN
// markers. Used by the file builder, the marker-scoped transform, and the
// audit-framework parity check. Single source of truth.
export function buildLlmsFullBody(): string {
  const lines: string[] = [];
  lines.push(LLMS_FULL_START);
  lines.push("");

  // Pillars first — they are the conversion engine.
  lines.push("## Pillar pages");
  lines.push("");
  for (const [pPath, entry] of Object.entries(PILLAR_SCHEMAS) as [string, PillarSchemaEntry][]) {
    const fw = entry.framework;
    lines.push(`### ${safeHeading(entry.title, pPath === "/" ? "OARC Digital" : pPath.slice(1).replace(/[-/]/g, " "))}`);
    lines.push(`Canonical: ${pillarCanonical(pPath)}`);
    lines.push("");
    emitOptionalField(lines, "**Description**", entry.description);
    if (fw) {
      emitOptionalField(lines, "**Value proposition**", fw.uniqueValueProp);
      const entityFocus = curateDiscoveryText(fw.entityFocus);
      const primaryIntent = curateDiscoveryText(fw.primaryIntent);
      const conversionGoal = curateDiscoveryText(fw.conversionGoal);
      if (entityFocus) lines.push(`**Entity focus**: ${entityFocus}`);
      if (primaryIntent) lines.push(`**Primary intent**: ${primaryIntent}`);
      if (conversionGoal) lines.push(`**Conversion goal**: ${conversionGoal}`);
      if (entityFocus || primaryIntent || conversionGoal) lines.push("");
      emitFacts(lines, fw.llmCitableFacts);
    }
    emitFaqs(lines, entry.faqs);
    lines.push("---");
    lines.push("");
  }

  // Services next — alphabetical by slug for stable output.
  lines.push("## Service pages");
  lines.push("");
  const serviceSlugs = Object.keys(SERVICE_SCHEMAS).sort();
  for (const slug of serviceSlugs) {
    const entry = SERVICE_SCHEMAS[slug] as ServiceSchemaEntry;
    const fw = entry.framework;
    lines.push(`### ${safeHeading(entry.title, slug.replace(/[-]/g, " "))}`);
    lines.push(`Canonical: ${serviceCanonical(slug)}`);
    lines.push("");
    emitOptionalField(lines, "**Description**", entry.description);
    // Features come from the ServiceSchemaEntry directly — same canonical
    // source the Service hasOfferCatalog node is built from. If a service
    // has no features, that is a data gap to fix at the source — never
    // silently paper over here.
    emitFeatures(lines, entry.features);
    if (fw) {
      emitOptionalField(lines, "**Value proposition**", fw.uniqueValueProp);
      const entityFocus = curateDiscoveryText(fw.entityFocus);
      const primaryIntent = curateDiscoveryText(fw.primaryIntent);
      const conversionGoal = curateDiscoveryText(fw.conversionGoal);
      if (entityFocus) lines.push(`**Entity focus**: ${entityFocus}`);
      if (primaryIntent) lines.push(`**Primary intent**: ${primaryIntent}`);
      if (conversionGoal) lines.push(`**Conversion goal**: ${conversionGoal}`);
      if (entityFocus || primaryIntent || conversionGoal) lines.push("");
      emitFacts(lines, fw.llmCitableFacts);
    }
    emitFaqs(lines, entry.faqs);
    lines.push("---");
    lines.push("");
  }

  // Task #135 — supplemental Core 60 stubs. Throws if a TOP_PAGES path
  // has no resolvable metadata, so a missing core page hard-fails the
  // generator AND its --check parity gate (gate:fast).
  const supplemental = buildSupplementalLlmsFullEntries();
  if (supplemental) {
    lines.push(supplemental);
  }

  lines.push(buildH360LlmsFullSection());

  lines.push(LLMS_FULL_END);
  return lines.join("\n");
}

// First-run / cold-start file: header + body + trailing newline. Only used
// when the file does not yet exist on disk.
export function buildLlmsFullFile(): string {
  return `${staticHeader()}${buildLlmsFullBody()}\n`;
}

// Marker-scoped replacement. Preserves everything OUTSIDE the AUTOGEN markers
// (human header tweaks, manual footer notes) and substitutes the body with
// the freshly-built autogen content. Idempotent: running twice produces the
// same bytes.
//
// If markers are missing entirely, we fall back to a full rewrite so the
// generator self-heals corrupt files. This is the same behavior the
// `--check` parity gate enforces — no markers means out-of-date.
export function applyLlmsFullTransform(current: string): string {
  const startIdx = current.indexOf(LLMS_FULL_START);
  const endIdx = current.indexOf(LLMS_FULL_END);
  const body = buildLlmsFullBody();
  if (startIdx === -1 || endIdx === -1 || endIdx < startIdx) {
    // Markers missing or malformed — rewrite the whole file from scratch.
    return buildLlmsFullFile();
  }
  const before = current.slice(0, startIdx);
  const after = current.slice(endIdx + LLMS_FULL_END.length);
  let next = `${before}${body}${after}`;

  // The discovery header is generator-owned too. Keep compact and full
  // outputs identical, including the Actions links, and make --check fail
  // if either copy drifts.
  const startHere = buildStartHereSection();
  const startHereIdx = next.indexOf(START_HERE_START);
  const endHereIdx = next.indexOf(START_HERE_END);
  if (startHereIdx >= 0 && endHereIdx > startHereIdx) {
    next =
      next.slice(0, startHereIdx) +
      startHere +
      next.slice(endHereIdx + START_HERE_END.length);
  } else {
    next = `${next.slice(0, next.indexOf(LLMS_FULL_START))}${startHere}\n\n${next.slice(next.indexOf(LLMS_FULL_START))}`;
  }
  return next;
}
