// Shared builder for `public/llms-full.txt`. Imported by the generator
// (`scripts/generate-llms-full-txt.ts`) AND the audit-framework parity gate
// so both sides reference one source of truth — no drift possible.
//
// The entire file is autogenerated from SERVICE_SCHEMAS + PILLAR_SCHEMAS.
// Hand-editing fails the audit. AUTOGEN markers wrap the body.

import { SERVICE_SCHEMAS, type ServiceSchemaEntry } from "./serviceSchemaConfig";
import { PILLAR_SCHEMAS, type PillarSchemaEntry } from "./pillarSchemaConfig";
import { NAP } from "./nap";

export const LLMS_FULL_PATH = "public/llms-full.txt";
export const LLMS_FULL_START = "<!-- AUTOGEN:LLMS-FULL:START -->";
export const LLMS_FULL_END = "<!-- AUTOGEN:LLMS-FULL:END -->";

function pillarCanonical(pPath: string): string {
  return pPath === "/" ? "https://oarcdigital.com/" : `https://oarcdigital.com${pPath}`;
}

function serviceCanonical(slug: string): string {
  return `https://oarcdigital.com/services/${slug}`;
}

function emitFaqs(lines: string[], faqs: { question: string; answer: string }[]) {
  if (!faqs?.length) return;
  lines.push("**FAQs**");
  lines.push("");
  for (const f of faqs) {
    lines.push(`Q: ${f.question}`);
    lines.push(`A: ${f.answer}`);
    lines.push("");
  }
}

function emitFacts(
  lines: string[],
  facts: { claim: string; source?: string }[],
) {
  if (!facts?.length) return;
  lines.push("**Cite-able facts**");
  lines.push("");
  for (const f of facts) {
    if (f.source) {
      lines.push(`- ${f.claim} (source: ${f.source})`);
    } else {
      lines.push(`- ${f.claim}`);
    }
  }
  lines.push("");
}

export function buildLlmsFullFile(): string {
  const lines: string[] = [];

  // Static header (regenerated on every run, kept outside markers visually
  // for human readers but still part of the byte-for-byte parity check).
  lines.push("# OARC Digital — Full Reference for AI Answer Engines");
  lines.push("");
  lines.push(
    "> Auto-generated from `lib/seo/serviceSchemaConfig.ts` + `lib/seo/pillarSchemaConfig.ts` by `scripts/generate-llms-full-txt.ts`. Do not hand-edit. Re-run the generator after every schema edit. Audit-framework verifies parity on every commit.",
  );
  lines.push("");
  lines.push(
    `Canonical NAP: ${NAP.name} | ${NAP.streetAddress}, ${NAP.addressLocality} ${NAP.postalCode}, Malta | ${NAP.phoneDisplay} | ${NAP.email}`,
  );
  lines.push("");
  lines.push("---");
  lines.push("");
  lines.push(LLMS_FULL_START);
  lines.push("");

  // Pillars first — they are the conversion engine.
  lines.push("## Pillar pages");
  lines.push("");
  for (const [pPath, entry] of Object.entries(PILLAR_SCHEMAS) as [string, PillarSchemaEntry][]) {
    const fw = entry.framework;
    lines.push(`### ${entry.title}`);
    lines.push(`Canonical: ${pillarCanonical(pPath)}`);
    lines.push("");
    lines.push("**Description**");
    lines.push(entry.description);
    lines.push("");
    if (fw) {
      lines.push("**Value proposition**");
      lines.push(fw.uniqueValueProp);
      lines.push("");
      lines.push(`**Entity focus**: ${fw.entityFocus}`);
      lines.push(`**Primary intent**: ${fw.primaryIntent}`);
      lines.push(`**Conversion goal**: ${fw.conversionGoal}`);
      lines.push("");
      emitFacts(lines, fw.llmCitableFacts);
    }
    emitFaqs(lines, entry.faqs);
    lines.push("---");
    lines.push("");
  }

  // Services next — alphabetical by slug for stable output.
  lines.push("## Service pages");
  lines.push("");
  const serviceSlugs = Object.keys(SERVICE_SCHEMAS).sort();
  for (const slug of serviceSlugs) {
    const entry = SERVICE_SCHEMAS[slug] as ServiceSchemaEntry;
    const fw = entry.framework;
    lines.push(`### ${entry.title}`);
    lines.push(`Canonical: ${serviceCanonical(slug)}`);
    lines.push("");
    lines.push("**Description**");
    lines.push(entry.description);
    lines.push("");
    if (fw) {
      lines.push("**Value proposition**");
      lines.push(fw.uniqueValueProp);
      lines.push("");
      lines.push(`**Entity focus**: ${fw.entityFocus}`);
      lines.push(`**Primary intent**: ${fw.primaryIntent}`);
      lines.push(`**Conversion goal**: ${fw.conversionGoal}`);
      lines.push("");
      emitFacts(lines, fw.llmCitableFacts);
    }
    emitFaqs(lines, entry.faqs);
    lines.push("---");
    lines.push("");
  }

  lines.push(LLMS_FULL_END);
  lines.push("");
  return lines.join("\n");
}
