// Shared builder for `public/llms-full.txt`. Imported by the generator
// (`scripts/generate-llms-full-txt.ts`) AND the audit-framework parity gate
// so both sides reference one source of truth — no drift possible.
//
// The autogenerated body is bounded by AUTOGEN markers. Anything OUTSIDE the
// markers (custom human-authored notes, footer signatures) is preserved by
// `applyLlmsFullTransform`. Hand-editing INSIDE the markers fails the audit.

import { SERVICE_SCHEMAS, type ServiceSchemaEntry } from "./serviceSchemaConfig";
import { PILLAR_SCHEMAS, type PillarSchemaEntry } from "./pillarSchemaConfig";
import { NAP } from "./nap";
import { buildSupplementalLlmsFullEntries } from "./llmsTxtGenerator";
import { buildH360LlmsFullSection } from "./h360LlmsGenerator";

export const LLMS_FULL_PATH = "public/llms-full.txt";
export const LLMS_FULL_START = "<!-- AUTOGEN:LLMS-FULL:START -->";
export const LLMS_FULL_END = "<!-- AUTOGEN:LLMS-FULL:END -->";

function pillarCanonical(pPath: string): string {
  return pPath === "/" ? "https://oarcdigital.com/" : `https://oarcdigital.com${pPath}`;
}

function serviceCanonical(slug: string): string {
  return `https://oarcdigital.com/services/${slug}`;
}

function emitFaqs(lines: string[], faqs: { question: string; answer: string }[]) {
  if (!faqs?.length) return;
  lines.push("**FAQs**");
  lines.push("");
  for (const f of faqs) {
    lines.push(`Q: ${f.question}`);
    lines.push(`A: ${f.answer}`);
    lines.push("");
  }
}

function emitFacts(
  lines: string[],
  facts: { claim: string; source?: string }[],
) {
  if (!facts?.length) return;
  lines.push("**Cite-able facts**");
  lines.push("");
  for (const f of facts) {
    if (f.source) {
      lines.push(`- ${f.claim} (source: ${f.source})`);
    } else {
      lines.push(`- ${f.claim}`);
    }
  }
  lines.push("");
}

function emitFeatures(lines: string[], features: { name: string }[] | undefined) {
  if (!features?.length) return;
  lines.push("**Features**");
  lines.push("");
  for (const f of features) {
    lines.push(`- ${f.name}`);
  }
  lines.push("");
}

function staticHeader(): string {
  const lines: string[] = [];
  lines.push("# OARC Digital — Full Reference for AI Answer Engines");
  lines.push("");
  lines.push(
    "> Auto-generated body between AUTOGEN markers below from `lib/seo/serviceSchemaConfig.ts` + `lib/seo/pillarSchemaConfig.ts` + `lib/seo/serviceSchemaExtras.ts` by `scripts/generate-llms-full-txt.ts`. Do not hand-edit INSIDE the markers — re-run the generator. Content OUTSIDE the markers is preserved across runs.",
  );
  lines.push("");
  lines.push(
    `Canonical NAP: ${NAP.name} | ${NAP.streetAddress}, ${NAP.addressLocality} ${NAP.postalCode}, Malta | ${NAP.phoneDisplay} | ${NAP.email}`,
  );
  lines.push("");
  lines.push("---");
  lines.push("");
  return lines.join("\n");
}

// The autogenerated body — everything between (and including) the AUTOGEN
// markers. Used by the file builder, the marker-scoped transform, and the
// audit-framework parity check. Single source of truth.
export function buildLlmsFullBody(): string {
  const lines: string[] = [];
  lines.push(LLMS_FULL_START);
  lines.push("");

  // Pillars first — they are the conversion engine.
  lines.push("## Pillar pages");
  lines.push("");
  for (const [pPath, entry] of Object.entries(PILLAR_SCHEMAS) as [string, PillarSchemaEntry][]) {
    const fw = entry.framework;
    lines.push(`### ${entry.title}`);
    lines.push(`Canonical: ${pillarCanonical(pPath)}`);
    lines.push("");
    lines.push("**Description**");
    lines.push(entry.description);
    lines.push("");
    if (fw) {
      lines.push("**Value proposition**");
      lines.push(fw.uniqueValueProp);
      lines.push("");
      lines.push(`**Entity focus**: ${fw.entityFocus}`);
      lines.push(`**Primary intent**: ${fw.primaryIntent}`);
      lines.push(`**Conversion goal**: ${fw.conversionGoal}`);
      lines.push("");
      emitFacts(lines, fw.llmCitableFacts);
    }
    emitFaqs(lines, entry.faqs);
    lines.push("---");
    lines.push("");
  }

  // Services next — alphabetical by slug for stable output.
  lines.push("## Service pages");
  lines.push("");
  const serviceSlugs = Object.keys(SERVICE_SCHEMAS).sort();
  for (const slug of serviceSlugs) {
    const entry = SERVICE_SCHEMAS[slug] as ServiceSchemaEntry;
    const fw = entry.framework;
    lines.push(`### ${entry.title}`);
    lines.push(`Canonical: ${serviceCanonical(slug)}`);
    lines.push("");
    lines.push("**Description**");
    lines.push(entry.description);
    lines.push("");
    // Features come from the ServiceSchemaEntry directly — same canonical
    // source the Service hasOfferCatalog node is built from. If a service
    // has no features, that is a data gap to fix at the source — never
    // silently paper over here.
    emitFeatures(lines, entry.features);
    if (fw) {
      lines.push("**Value proposition**");
      lines.push(fw.uniqueValueProp);
      lines.push("");
      lines.push(`**Entity focus**: ${fw.entityFocus}`);
      lines.push(`**Primary intent**: ${fw.primaryIntent}`);
      lines.push(`**Conversion goal**: ${fw.conversionGoal}`);
      lines.push("");
      emitFacts(lines, fw.llmCitableFacts);
    }
    emitFaqs(lines, entry.faqs);
    lines.push("---");
    lines.push("");
  }

  // Task #135 — supplemental Core 60 stubs. Throws if a TOP_PAGES path
  // has no resolvable metadata, so a missing core page hard-fails the
  // generator AND its --check parity gate (gate:fast).
  const supplemental = buildSupplementalLlmsFullEntries();
  if (supplemental) {
    lines.push(supplemental);
  }

  lines.push(buildH360LlmsFullSection());

  lines.push(LLMS_FULL_END);
  return lines.join("\n");
}

// First-run / cold-start file: header + body + trailing newline. Only used
// when the file does not yet exist on disk.
export function buildLlmsFullFile(): string {
  return `${staticHeader()}${buildLlmsFullBody()}\n`;
}

// Marker-scoped replacement. Preserves everything OUTSIDE the AUTOGEN markers
// (human header tweaks, manual footer notes) and substitutes the body with
// the freshly-built autogen content. Idempotent: running twice produces the
// same bytes.
//
// If markers are missing entirely, we fall back to a full rewrite so the
// generator self-heals corrupt files. This is the same behavior the
// `--check` parity gate enforces — no markers means out-of-date.
export function applyLlmsFullTransform(current: string): string {
  const startIdx = current.indexOf(LLMS_FULL_START);
  const endIdx = current.indexOf(LLMS_FULL_END);
  const body = buildLlmsFullBody();
  if (startIdx === -1 || endIdx === -1 || endIdx < startIdx) {
    // Markers missing or malformed — rewrite the whole file from scratch.
    return buildLlmsFullFile();
  }
  const before = current.slice(0, startIdx);
  const after = current.slice(endIdx + LLMS_FULL_END.length);
  return `${before}${body}${after}`;
}
