import type { StackPreviewKind } from './standaloneProductTypes';
import type { StandaloneExtras } from './buildStandalone';

const st = (id: string, label: string, short: string, detail: string, preview: StackPreviewKind) =>
  ({ id, label, short, detail, preview }) as const;

const sig = (term: string, vol: number, trend: '↑' | '→' | '↓' = '↑') => ({ term, vol, trend }) as const;

const wk = (week: number, score: number, rank: number, label: string, highlight?: string) =>
  ({ week, score, rank, label, highlight }) as const;

export const STANDALONE_EXTRAS: Record<string, StandaloneExtras> = {
  googleVisibility: {
    doctrine: 'Posting photos is hygiene. Winning visibility is SEO + AEO + AI search — engineered weekly.',
    metric: { value: '847→37', label: 'searches that become walk-ins' },
    stack: {
      title: 'Photos are 5%. This is the other 95%.',
      subtitle: 'SEO, AEO, AI search, LLM files, articles, GBP — one engine. You see the post; we run the physics.',
      items: [
        st('seo', 'Local SEO', 'Rank for real searches', 'Malta neighbourhoods · competitor gaps', 'maps-rank'),
        st('aeo', 'AEO', 'Win AI answers', 'FAQ schema · speakable copy', 'aeo-answer'),
        st('ai', 'AI search', 'ChatGPT · Gemini', 'Structured facts machines cite', 'ai-chat'),
        st('llm', 'LLM index', 'llms.txt', 'Entity graph for crawlers', 'llm-file'),
        st('art', 'Articles', 'Keyword content', 'Copywriter + trend data', 'article'),
        st('gbp', 'GBP ops', 'Posts · replies', 'Visible tip of the stack', 'gbp-post'),
      ],
    },
    signals: {
      title: 'We target keywords that bring covers — not vanity traffic.',
      subtitle: 'ARC reads gaps. Copywriter turns trend terms into posts and articles you approve.',
      boardLabel: 'MALTA · LIVE KEYWORD PULSE',
      items: [sig('best restaurant sliema', 92), sig('seafood restaurant malta', 78), sig('restaurant near me valletta', 85), sig('lampuki season malta', 64), sig('romantic dinner malta', 71)],
      ctaLine: 'Next post targets',
    },
    progress: {
      title: 'Month 1 to month 3 — score, rank, calls on WhatsApp.',
      subtitle: 'We know what moves first in Malta. You see it weekly, not in a PDF.',
      scoreLabel: 'Profile score',
      rankLabel: 'Maps rank',
      weeks: [wk(1, 42, 14, 'Claimed · baseline audit'), wk(4, 68, 9, '4 posts · review replies live'), wk(8, 81, 5, 'Articles indexing · AI cites'), wk(12, 91, 3, '847 searches → 37 calls', '847 → 37 calls')],
    },
    compare: {
      title: 'Stale profile vs visibility engine',
      subtitle: 'Same search. Different outcome.',
      brainLine: 'BrightLocal gives PDFs. H360 runs SEO, AEO, AI search, and GBP for Malta operators.',
      badLabel: 'DIY · STALE', goodLabel: 'H360 VISIBILITY',
      badNote: 'Last post: 8 months ago', goodNote: 'SEO · AEO · AI · posts this week',
      badMetric: '#12', goodMetric: '#3',
      goodExtra: { left: '847', leftLabel: 'searches', right: '37', rightLabel: 'calls' },
      premiumVisual: 'google-maps-rank',
    },
  },

  reviews: {
    doctrine: 'One tap to the review form beats a generic Maps QR every time.',
    metric: { value: '3×', label: 'more reviews in 90 days' },
    stack: {
      title: 'Reviews are visibility fuel — we engineer the ask.',
      subtitle: 'QR timing · AEO trust signals · Google ranking lift · owner replies — not a paper sign.',
      items: [
        st('qr', 'Direct QR', 'One tap', 'Review form — not Maps search', 'review-qr'),
        st('time', 'Smart timing', 'After the meal', 'When guests are happiest', 'review-climb'),
        st('aeo', 'AEO trust', 'Star schema', 'AI cites your rating', 'aeo-answer'),
        st('seo', 'Maps SEO', 'Review velocity', 'Fresh reviews climb rank', 'maps-rank'),
        st('reply', 'Owner replies', 'AI draft', 'You approve in one tap', 'gbp-post'),
      ],
    },
    signals: {
      title: 'Target the searches reviews unlock.',
      subtitle: '“Best rated restaurant Malta” — we grow the signal that wins it.',
      boardLabel: 'REVIEW · INTENT SIGNALS',
      items: [sig('best rated restaurant malta', 88), sig('google reviews sliema', 76), sig('restaurant 4.8 stars malta', 82), sig('trusted restaurant valletta', 70)],
      ctaLine: 'Review push aligned to',
    },
    progress: {
      title: 'Stars climb — you watch the number.',
      subtitle: 'From 12 reviews to a Maps weapon.',
      scoreLabel: 'Review count',
      rankLabel: 'Avg rating',
      weeks: [wk(1, 12, 4, 'QR live on every table'), wk(4, 48, 5, '4.6★ · replies going live'), wk(8, 112, 5, '4.7★ · AI cites your stars'), wk(12, 186, 5, '3× reviews · Maps climb', '4.8★ · 186 reviews')],
    },
    compare: {
      title: 'Free QR vs direct review form',
      subtitle: '3–4 taps vs one tap — that is the whole game.',
      brainLine: 'Sunday needs a €250 terminal. H360 needs a tent card.',
      badLabel: 'FREE MAPS QR', goodLabel: 'H360 REVIEWS',
      badNote: '3–4 taps · most quit', goodNote: 'Direct to review form',
      badMetric: '12 reviews', goodMetric: '186 reviews',
    },
  },

  social: {
    doctrine: 'Creation beats scheduling. Your feed should look alive before service starts.',
    metric: { value: '4/wk', label: 'finished posts — not blank calendars' },
    stack: {
      title: 'Not Buffer. Completed restaurant content.',
      subtitle: 'Photo edit · captions · Reels · paid boost · AEO social signals — weekly.',
      items: [
        st('photo', 'Food edit', 'Any phone shot', 'Pro lighting · crop · colour', 'social-post'),
        st('copy', 'Copywriter', 'Your tone', 'Hashtags · Malta trends', 'article'),
        st('reel', 'Reels', 'Platform-native', 'What Instagram pushes now', 'reels'),
        st('ads', 'Paid boost', 'Local reach', '€20 → 2k locals', 'ad-boost'),
        st('aeo', 'AEO', 'Entity links', 'Social → site → Google', 'aeo-answer'),
      ],
    },
    signals: {
      title: 'Trend keywords become posts — not generic fluff.',
      subtitle: '“Lampuki special” beats “We love our customers.”',
      boardLabel: 'SOCIAL · TREND PULSE',
      items: [sig('lampuki malta instagram', 74), sig('valletta dinner reel', 68), sig('malta food blogger', 62), sig('book table instagram', 80)],
      ctaLine: 'This week\'s post angle',
    },
    progress: {
      title: 'Empty feed → booked-out weekend.',
      subtitle: 'See posts go live — not strategy decks.',
      scoreLabel: 'Posts / month',
      rankLabel: 'Reach index',
      weeks: [wk(1, 0, 2, 'Archive audit · tone set'), wk(4, 12, 5, '3 posts/wk live'), wk(8, 16, 7, 'Reels + boost running'), wk(12, 16, 9, 'Feed looks pro · bookings ↑', '4 posts/wk · ads on')],
    },
    compare: {
      title: 'Empty feed vs completed posts',
      subtitle: 'Schedulers publish — they do not create.',
      brainLine: '€1,000/mo agencies write decks. H360 delivers ready posts.',
      badLabel: 'BUFFER / DIY', goodLabel: 'H360 SOCIAL',
      badNote: 'No posts in 3 weeks', goodNote: 'Ready to publish',
      badMetric: '0/wk', goodMetric: '4/wk',
      premiumVisual: 'social-feed-mock',
    },
  },

  website: {
    doctrine: 'Own the URL. TripAdvisor is a billboard — your site is the front door.',
    metric: { value: '10 min', label: 'menu photo to live site' },
    stack: {
      title: 'A website Google and AI can read.',
      subtitle: 'Live site · schema · menu sync · SEO · AEO · order/book links.',
      items: [
        st('live', 'Live site', 'yourrestaurant.mt', 'Menu · hours · book', 'website-live'),
        st('schema', 'Schema', 'Restaurant JSON-LD', 'Google + AI parse you', 'schema'),
        st('menu', 'Menu sync', 'Photo → site', '10-minute updates', 'menu-sync'),
        st('seo', 'Local SEO', 'On-page', 'Malta keywords baked in', 'maps-rank'),
        st('aeo', 'AEO', 'FAQ blocks', 'AI answer-ready copy', 'aeo-answer'),
      ],
    },
    signals: {
      title: 'Pages that rank and convert walk-ins.',
      subtitle: 'Every page targets a search intent — not a Wix template.',
      boardLabel: 'SITE · SEARCH INTENT',
      items: [sig('restaurant menu malta', 86), sig('book table malta online', 79), sig('maltese restaurant website', 65), sig('order direct restaurant malta', 72)],
      ctaLine: 'Next page optimises',
    },
    progress: {
      title: 'No site → #1 on your name search.',
      subtitle: 'Live in days — not months.',
      scoreLabel: 'Site score',
      rankLabel: 'Google index',
      weeks: [wk(1, 20, 0, 'No site · TripAdvisor owns story'), wk(2, 65, 8, 'Live · menu + schema'), wk(6, 82, 4, 'SEO pages indexing'), wk(12, 94, 2, '1 in 5 visitors walk in', 'Site → walk-ins')],
    },
    compare: {
      title: 'No website vs owned front door',
      subtitle: 'TripAdvisor takes the click. Your site keeps it.',
      brainLine: 'Wix DIY with no SEO. H360 builds for Google and AI from day one.',
      badLabel: 'NO SITE', goodLabel: 'H360 WEBSITE',
      badNote: 'TripAdvisor owns story', goodNote: 'Menu · book · order',
      badMetric: '0%', goodMetric: '20%',
      premiumVisual: 'website-before-after',
    },
  },

  rest: {
    doctrine: 'One source of truth beats twelve tabs open during Friday rush.',
    metric: { value: '1 stack', label: 'menu · kitchen · owner — connected' },
    stack: {
      title: 'The full operating system — not another app.',
      subtitle: 'Digital menu · kitchen screen · owner dashboard · data · SEO hooks.',
      items: [
        st('menu', 'Digital menu', 'One source', 'Updates everywhere', 'menu-sync'),
        st('kit', 'Kitchen screen', 'No shouting', 'Tickets print · display', 'kitchen-ticket'),
        st('own', 'Owner dash', 'One number', 'Covers · revenue · alerts', 'owner-dash'),
        st('sync', 'Connected', 'All modules', 'Order · pay · book talk', 'connected'),
        st('data', 'ARC data', 'Decisions', 'What to fix this week', 'trend'),
      ],
    },
    signals: {
      title: 'Operational data feeds marketing.',
      subtitle: 'Kitchen mistakes down. Owner knows tonight before service.',
      boardLabel: 'SYSTEM · LIVE SIGNALS',
      items: [sig('menu 86 items', 90), sig('avg ticket €28', 75), sig('friday forecast 52', 82), sig('margin alert pasta', 68)],
      ctaLine: 'Owner alert',
    },
    progress: {
      title: 'Chaos → one screen.',
      subtitle: 'Menu, kitchen, owner — finally aligned.',
      scoreLabel: 'Modules live',
      rankLabel: 'Error rate',
      weeks: [wk(1, 1, 8, 'Paper menu · shouting kitchen'), wk(4, 3, 5, 'Menu + kitchen live'), wk(8, 4, 3, 'Owner dash + alerts'), wk(12, 5, 1, 'Full stack connected', '1 truth · 0 shouting')],
    },
    compare: {
      title: 'Twelve tabs vs one system',
      subtitle: 'Toast needs POS. H360 needs your menu photo.',
      brainLine: 'US POS bundles do not fit Malta. H360 connects what you already run.',
      badLabel: 'DISCONNECTED', goodLabel: 'H360 REST',
      badNote: 'Menu · kitchen · owner separate', goodNote: 'One sync · one dash',
      badMetric: '12 apps', goodMetric: '1 stack',
      premiumVisual: 'rest-system-hub',
    },
  },

  booking: {
    doctrine: 'The notebook dies tonight. Slots lock. You know who is coming.',
    metric: { value: '€0', label: 'per-cover platform tax' },
    stack: {
      title: 'Bookings without OpenTable tax.',
      subtitle: 'Link · lock · confirm · WhatsApp morning list · SEO book button.',
      items: [
        st('link', 'Booking link', 'Instagram · Google', 'Guests book 2am', 'booking-slot'),
        st('lock', 'Slot lock', 'Real-time', 'No double bookings', 'confirm'),
        st('wait', 'Waitlist', 'Table free', 'SMS when ready', 'waitlist'),
        st('am', 'Morning list', 'WhatsApp', 'Who\'s coming tonight', 'wa-reply'),
        st('seo', 'SEO', 'Book button', 'Google · site · AEO', 'website-live'),
      ],
    },
    signals: {
      title: 'Capture tourists who never call.',
      subtitle: 'Online book intent — not phone tag during service.',
      boardLabel: 'BOOKING · INTENT',
      items: [sig('book restaurant sliema', 84), sig('table reservation malta', 77), sig('dinner booking valletta', 73), sig('instagram book link', 69)],
      ctaLine: 'Slot promoted on',
    },
    progress: {
      title: 'Notebook → full Friday.',
      subtitle: 'Double bookings stop. No-shows drop.',
      scoreLabel: 'Online bookings',
      rankLabel: 'No-show %',
      weeks: [wk(1, 2, 40, 'Notebook only'), wk(4, 18, 22, 'Link live · slots lock'), wk(8, 35, 12, 'Confirmations on'), wk(12, 48, 8, 'Morning list every day', '48 online / week')],
    },
    compare: {
      title: 'OpenTable fees vs flat booking',
      subtitle: '30 covers should not cost €60 in platform tax.',
      brainLine: 'ResDiary is €199/mo for algorithms you do not need. H360 replaces the notebook.',
      badLabel: 'OPENTABLE', goodLabel: 'H360 BOOKING',
      badNote: '€2/cover · 30% no-show', goodNote: 'Flat · confirmations',
      badMetric: '€60/night', goodMetric: '€0/cover',
      premiumVisual: 'booking-fee-compare',
    },
  },

  order: {
    doctrine: 'Commission is a tax. Direct orders keep margin and the guest relationship.',
    metric: { value: '€0', label: 'commission per table order' },
    stack: {
      title: 'Own the order — not the aggregator.',
      subtitle: 'QR menu · kitchen ticket · margin · SEO order link · guest data.',
      items: [
        st('qr', 'Table QR', 'Scan · tap', 'No waiter pad errors', 'order-qr'),
        st('kit', 'Kitchen', 'Ticket prints', 'No shouting', 'kitchen-print'),
        st('mar', 'Margin', '€0 fee', 'Keep full dish price', 'margin'),
        st('seo', 'Discovery', 'Google · site', 'Order link everywhere', 'website-live'),
        st('data', 'Guest data', 'Yours', 'WhatsApp win-back later', 'wa-segment'),
      ],
    },
    signals: {
      title: 'Shift “order near me” to your link.',
      subtitle: 'Every direct order is margin you were giving Wolt.',
      boardLabel: 'ORDER · DIRECT INTENT',
      items: [sig('order food malta direct', 71), sig('qr menu restaurant', 83), sig('takeaway no commission', 77), sig('table ordering malta', 80)],
      ctaLine: 'Push order link on',
    },
    progress: {
      title: 'Week 1 → commission saved.',
      subtitle: 'See direct orders climb — feel margin return.',
      scoreLabel: 'Direct orders/day',
      rankLabel: 'Commission saved',
      weeks: [wk(1, 3, 0, 'Wolt only'), wk(4, 12, 400, 'QR on every table'), wk(8, 28, 1200, 'Regulars order direct'), wk(12, 45, 3300, 'Margin in your till', '≈ €3,300/mo saved')],
    },
    compare: {
      title: 'Same busy night. Two outcomes.',
      subtitle: '22% commission vs €0 on the same €500/day.',
      brainLine: 'On €500/day at 22% you pay ~€3,300/month. Direct QR keeps it.',
      badLabel: 'WOLT / BOLT', goodLabel: 'H360 ORDER',
      badNote: '22% per order', goodNote: '€0 commission',
      badMetric: '−€3.3k/mo', goodMetric: 'Keep all',
      customCompare: 'order-margin',
    },
  },

  pay: {
    doctrine: 'Hardware is a tax. A tent card on the table is the whole terminal.',
    metric: { value: '10 sec', label: 'pay-at-table — no bill chase' },
    stack: {
      title: 'Pay without €250 terminals.',
      subtitle: 'QR pay · split bill · tips · faster turns · happy staff.',
      items: [
        st('qr', 'Table QR', 'Tent card', 'Guest pays when ready', 'pay-qr'),
        st('split', 'Split bill', 'Party of 6', 'Each pays their share', 'split-bill'),
        st('tip', 'Tips', 'Digital', 'Staff revenue ↑', 'tips'),
        st('turn', 'Faster turns', 'No bill wait', 'More covers/night', 'trend'),
        st('seo', 'Trust', 'Google', '“Pay at table” in reviews', 'review-climb'),
      ],
    },
    signals: {
      title: 'Guests hate the bill wait — fix the leak.',
      subtitle: '15-minute bill chase kills turns on Friday.',
      boardLabel: 'PAY · FRICTION SIGNALS',
      items: [sig('pay at table malta', 66), sig('split bill restaurant', 72), sig('fast checkout dining', 58), sig('contactless pay restaurant', 74)],
      ctaLine: 'QR live on',
    },
    progress: {
      title: 'Bill wait → 10-second checkout.',
      subtitle: 'Tables turn faster. Tips often rise.',
      scoreLabel: 'Avg pay time',
      rankLabel: 'Table turns',
      weeks: [wk(1, 15, 3, 'Waiter chases bills'), wk(2, 8, 4, 'QR on tables'), wk(6, 3, 5, 'Splits on phone'), wk(12, 1, 6, '10 sec checkout', 'Turns ↑ · tips ↑')],
    },
    compare: {
      title: 'Sunday terminal vs tent card',
      subtitle: '€250/table hardware vs printed QR.',
      brainLine: 'Sunday wants €3,750 for 15 tables. H360 wants a tent card.',
      badLabel: 'SUNDAY TERMINAL', goodLabel: 'H360 PAY',
      badNote: '€250/table hardware', goodNote: 'QR tent card',
      badMetric: '€3,750', goodMetric: '€0 HW',
      premiumVisual: 'pay-terminal-compare',
    },
  },

  stamp: {
    doctrine: 'Stamps should credit themselves — not live in a waiter\'s pocket.',
    metric: { value: '8th free', label: 'automatic — no paper card' },
    stack: {
      title: 'Loyalty that runs without staff friction.',
      subtitle: 'Wallet stamp · auto-credit · reward ping · win-back · AEO loyalty copy.',
      items: [
        st('wallet', 'Digital stamp', 'Phone wallet', 'No paper to lose', 'stamp-wallet'),
        st('auto', 'Auto-credit', 'No scan', 'Staff forget-proof', 'auto-stamp'),
        st('reward', '8th free', 'Ping', 'Guest chases last stamp', 'reward'),
        st('wa', 'Win-back', 'WhatsApp', 'Lapsed guests return', 'wa-offer'),
        st('seo', 'Reviews', 'Happy regulars', 'More Google stars', 'review-climb'),
      ],
    },
    signals: {
      title: 'Repeat visits are cheaper than ads.',
      subtitle: 'Track regulars — not hope they remember a paper card.',
      boardLabel: 'LOYALTY · SIGNALS',
      items: [sig('loyalty card restaurant', 70), sig('repeat customers malta', 76), sig('stamp card digital', 68), sig('regulars restaurant', 82)],
      ctaLine: 'Win-back targets',
    },
    progress: {
      title: 'Paper cards → automatic regulars.',
      subtitle: 'See stamps credit — see guests return.',
      scoreLabel: 'Active stamps',
      rankLabel: 'Return rate',
      weeks: [wk(1, 5, 12, 'Paper cards · forged'), wk(4, 40, 22, 'Wallet live'), wk(8, 120, 35, 'Auto-credit running'), wk(12, 200, 48, 'Regulars ↑', '8th free · auto')],
    },
    compare: {
      title: 'Paper card vs wallet stamp',
      subtitle: 'Lost · forged · staff forgets to stamp.',
      brainLine: 'Paper dies in wallets. H360 stamps credit on visit — automatically.',
      badLabel: 'PAPER CARD', goodLabel: 'H360 STAMP',
      badNote: 'Lost · forged', goodNote: 'Auto-credit',
      badMetric: '☐☐☐☐', goodMetric: '7/8',
    },
  },

  pass: {
    doctrine: 'Nobody downloads a restaurant app. Wallet pass — one tap.',
    metric: { value: '1 tap', label: 'add to Apple & Google Wallet' },
    stack: {
      title: 'Loyalty in the wallet — not another app.',
      subtitle: 'Pass · visit tracking · rewards · push · SEO loyalty page.',
      items: [
        st('add', 'Wallet pass', '1 tap add', 'Apple · Google', 'pass-add'),
        st('visit', 'Visit track', 'Auto', 'Every cover counted', 'visit-ping'),
        st('reward', 'Rewards', 'Tier unlock', 'Push on visit 5', 'reward'),
        st('wa', 'WhatsApp', 'Win-back', 'Lapsed → offer', 'wa-offer'),
        st('aeo', 'AEO', 'Loyalty FAQ', 'AI knows your program', 'aeo-answer'),
      ],
    },
    signals: {
      title: 'Guests keep passes — they delete apps.',
      subtitle: 'Wallet = always on the phone.',
      boardLabel: 'PASS · RETENTION',
      items: [sig('apple wallet loyalty', 74), sig('restaurant loyalty malta', 71), sig('digital loyalty card', 69), sig('repeat diner program', 77)],
      ctaLine: 'Reward push for',
    },
    progress: {
      title: 'App nobody opens → wallet they keep.',
      subtitle: 'Passes installed · visits tracked.',
      scoreLabel: 'Passes installed',
      rankLabel: 'Return visits',
      weeks: [wk(1, 0, 8, 'No loyalty'), wk(4, 85, 18, 'Wallet live'), wk(8, 220, 32, 'Rewards unlocking'), wk(12, 380, 44, 'Regulars on autopilot', '380 passes')],
    },
    compare: {
      title: 'Restaurant app vs wallet pass',
      subtitle: 'Downloads die. Wallet stays.',
      brainLine: 'Custom apps cost thousands. Wallet pass is one tap — H360 ships it.',
      badLabel: 'CUSTOM APP', goodLabel: 'H360 PASS',
      badNote: 'Nobody downloads', goodNote: 'Wallet · 1 tap',
      badMetric: '4% install', goodMetric: '68% add',
    },
  },

  send: {
    doctrine: 'Personal beats blast. WhatsApp is where Malta actually reads.',
    metric: { value: '47', label: 'lapsed guests reached this month' },
    stack: {
      title: 'WhatsApp that brings people back.',
      subtitle: 'Segments · offers · book link · AEO · no spam blasts.',
      items: [
        st('seg', 'Segments', 'Who lapsed', '30/60/90 day rules', 'wa-segment'),
        st('offer', 'Smart offer', 'Personal', 'Maria · free dessert', 'wa-offer'),
        st('book', 'Book reply', 'YES → table', 'One thread', 'wa-reply'),
        st('seo', 'Google', 'Click to chat', 'Profile link', 'gbp-post'),
        st('aeo', 'AEO', 'FAQ', '“WhatsApp order?” answered', 'aeo-answer'),
      ],
    },
    signals: {
      title: 'Win-back cheaper than new ads.',
      subtitle: 'Guests who already trust you — one message away.',
      boardLabel: 'WHATSAPP · SEGMENTS',
      items: [sig('whatsapp restaurant malta', 81), sig('win back customers', 75), sig('restaurant offer message', 70), sig('book via whatsapp', 78)],
      ctaLine: 'Campaign targets',
    },
    progress: {
      title: 'Forgotten → booked again.',
      subtitle: 'See replies turn into covers.',
      scoreLabel: 'Messages sent',
      rankLabel: 'Rebook rate',
      weeks: [wk(1, 0, 0, 'No list'), wk(4, 120, 15, 'Segments live'), wk(8, 280, 28, 'Offers personal'), wk(12, 420, 38, 'Maria orders again', '38% rebook')],
    },
    compare: {
      title: 'Broadcast spam vs smart follow-up',
      subtitle: 'Generic blasts get muted. Personal wins.',
      brainLine: 'Mailchimp for restaurants misses the channel. H360 uses WhatsApp the way Malta does.',
      badLabel: 'BLAST', goodLabel: 'H360 SEND',
      badNote: 'Muted · reported', goodNote: 'Personal · booked',
      badMetric: '2% reply', goodMetric: '38% rebook',
    },
  },

  text: {
    doctrine: 'SMS opens. Email dies in promotions. Win back who stopped visiting.',
    metric: { value: '98%', label: 'SMS open rate vs email' },
    stack: {
      title: 'SMS win-back — opt-in, not spam.',
      subtitle: 'Wallet opt-in · short text · book link · AEO compliance copy.',
      items: [
        st('opt', 'Opt-in', 'Wallet pass', 'No list upload', 'pass-add'),
        st('win', 'Win-back', 'Short SMS', 'We miss you — book', 'sms-winback'),
        st('open', 'Opens', '98%', 'Tap book link', 'sms-open'),
        st('book', 'Books', 'Table locked', 'Covers return', 'booking-slot'),
        st('seo', 'SEO', 'Offer page', 'Indexed landing', 'website-live'),
      ],
    },
    signals: {
      title: 'Reach guests email cannot.',
      subtitle: 'One line · one link · one booking.',
      boardLabel: 'SMS · WIN-BACK',
      items: [sig('restaurant sms marketing', 72), sig('win back diner sms', 68), sig('text offer restaurant', 65), sig('book table sms link', 74)],
      ctaLine: 'SMS targets',
    },
    progress: {
      title: 'Silent regulars → Friday covers.',
      subtitle: 'Track open · tap · book.',
      scoreLabel: 'SMS sent',
      rankLabel: 'Bookings from SMS',
      weeks: [wk(1, 0, 0, 'No reach'), wk(4, 80, 6, 'Opt-in live'), wk(8, 200, 18, 'Win-back running'), wk(12, 320, 32, 'Covers return', '32 rebooks')],
    },
    compare: {
      title: 'Email promo vs SMS win-back',
      subtitle: 'Promotions tab vs lock screen.',
      brainLine: 'Email gets 20% open if lucky. SMS gets read. H360 uses wallet opt-in — compliant.',
      badLabel: 'EMAIL BLAST', goodLabel: 'H360 TEXT',
      badNote: '20% open', goodNote: '98% open',
      badMetric: '2% click', goodMetric: '24% book',
    },
  },

  event: {
    doctrine: 'Event night needs a headcount — not a prayer and a Facebook post.',
    metric: { value: '−60%', label: 'no-shows with reminders' },
    stack: {
      title: 'Fill the room on event night.',
      subtitle: 'Event page · RSVP · cap · reminders · social · Google post.',
      items: [
        st('page', 'Event page', 'Branded', 'Not generic Eventbrite', 'event-rsvp'),
        st('cap', 'RSVP cap', 'Sold out', 'Know headcount', 'soldout'),
        st('rem', 'Reminders', '24h before', 'No-shows drop', 'reminder'),
        st('social', 'Auto post', 'SOCIAL + GBP', 'Reach beyond followers', 'social-post'),
        st('staff', 'Staff calc', 'Covers → roster', 'Schedule in STAFF', 'roster-wa'),
      ],
    },
    signals: {
      title: 'Promote once — fill with RSVPs.',
      subtitle: 'Facebook reach is 5%. RSVPs are real.',
      boardLabel: 'EVENT · FILL SIGNALS',
      items: [sig('live music malta restaurant', 76), sig('wine dinner event malta', 68), sig('restaurant event booking', 81), sig('friday night event valletta', 72)],
      ctaLine: 'Event promoted on',
    },
    progress: {
      title: '12 people knew → sold out.',
      subtitle: 'RSVPs · reminders · headcount.',
      scoreLabel: 'RSVPs',
      rankLabel: 'Show rate',
      weeks: [wk(1, 8, 50, 'Facebook post only'), wk(2, 28, 72, 'Event page live'), wk(4, 50, 88, 'Sold out · reminders'), wk(8, 50, 94, 'Next event easier', '50/50 confirmed')],
    },
    compare: {
      title: 'Eventbrite vs branded RSVP',
      subtitle: '3% ticket fee · generic page · yoga class vibes.',
      brainLine: 'Eventbrite lists you beside corporate training. H360 is your restaurant\'s night.',
      badLabel: 'EVENTBRITE', goodLabel: 'H360 EVENT',
      badNote: 'Fees · generic', goodNote: 'Branded · capped',
      badMetric: '12 RSVPs', goodMetric: '50 RSVPs',
      premiumVisual: 'event-rsvp-fill',
    },
  },

  analytics: {
    doctrine: '"Felt busy" is not data. One honest number every night builds the road up.',
    metric: { value: '1 #', label: 'at close — trends without a POS' },
    stack: {
      title: 'Analytics without a POS.',
      subtitle: 'Daily total · trends · forecast · WhatsApp reminder · owner decisions.',
      items: [
        st('num', 'One number', '€ at close', '30 seconds', 'daily-num'),
        st('trend', 'Trends', '7/30 day', 'Rolling averages', 'trend'),
        st('forecast', 'Forecast', 'Friday', 'Covers expected', 'forecast'),
        st('wa', 'WhatsApp', '9pm ping', 'Forgot? Remind', 'wa-reply'),
        st('seo', 'Marketing', 'Tie to H360', 'See what moved rank', 'maps-rank'),
      ],
    },
    signals: {
      title: 'Operational truth — not gut feel.',
      subtitle: 'One number nightly beats a spreadsheet nobody updates.',
      boardLabel: 'ANALYTICS · TRENDS',
      items: [sig('friday vs last friday', 88), sig('summer tourism lift', 82), sig('avg ticket trend', 75), sig('slow tuesday alert', 70)],
      ctaLine: 'Alert triggered',
    },
    progress: {
      title: 'Gut feel → trend line.',
      subtitle: 'Type €1,200 — see the road.',
      scoreLabel: 'Days logged',
      rankLabel: 'Trend clarity',
      weeks: [wk(1, 3, 10, 'Notebook guess'), wk(4, 22, 45, 'Daily WhatsApp habit'), wk(8, 45, 72, 'Seasonal pattern clear'), wk(12, 60, 90, 'Forecast Friday', '€1,200 → trend')],
    },
    compare: {
      title: 'Spreadsheet vs one number',
      subtitle: 'Nobody updates Excel. WhatsApp gets the truth.',
      brainLine: '7Shifts needs POS data. H360 needs: "I made €1,200 today."',
      badLabel: 'SPREADSHEET', goodLabel: 'H360 ANALYTICS',
      badNote: 'Stale · ignored', goodNote: '9pm WhatsApp',
      badMetric: '???', goodMetric: '€1,200',
      premiumVisual: 'analytics-trend',
    },
  },

  recipe: {
    doctrine: 'Tomatoes doubled. Portions crept. The menu must tell the truth.',
    metric: { value: '52%', label: 'real margin — not chef guesswork' },
    stack: {
      title: 'Know profit per plate — kill the leaks.',
      subtitle: 'Ingredient cost · portion drift · menu engineering · alerts.',
      items: [
        st('cost', 'Dish cost', 'Per plate', 'Ingredients once', 'dish-cost'),
        st('margin', 'Margin bar', 'Real %', 'Not chef guess', 'margin-bar'),
        st('alert', 'Price alert', 'Tomato +40%', 'Fix menu price', 'stock-check'),
        st('menu', 'Menu fix', '86 loser', 'Promote winner', 'menu-sync'),
        st('data', 'Owner dash', 'Weekly', 'What to change', 'owner-dash'),
      ],
    },
    signals: {
      title: 'Food cost moved — menu must follow.',
      subtitle: 'Lampuki season vs summer — margins shift.',
      boardLabel: 'RECIPE · MARGIN SIGNALS',
      items: [sig('pasta margin drop', 85), sig('lampuki cost spike', 78), sig('portion creep', 72), sig('hero dish profit', 80)],
      ctaLine: 'Fix dish',
    },
    progress: {
      title: 'Think 70% → know 52%.',
      subtitle: 'See losers before they sink the month.',
      scoreLabel: 'Dishes costed',
      rankLabel: 'Avg margin',
      weeks: [wk(1, 5, 45, 'Chef guesswork'), wk(4, 20, 58, 'Top dishes costed'), wk(8, 35, 65, 'Alerts on ingredients'), wk(12, 48, 72, 'Menu repriced', '72% avg winners')],
    },
    compare: {
      title: 'Guesswork vs plate-level truth',
      subtitle: 'US tools at $199/mo — overkill for 40 covers.',
      brainLine: 'MarketMan wants POS integration. H360 wants your ingredient list once.',
      badLabel: 'GUESSWORK', goodLabel: 'H360 RECIPE',
      badNote: 'Think 70% margin', goodNote: 'Know 52% real',
      badMetric: '???%', goodMetric: '72%',
      premiumVisual: 'recipe-margin',
    },
  },

  inventory: {
    doctrine: 'The chef knew Tuesday. Nobody wrote it down. That ends here.',
    metric: { value: '30s', label: 'closing check — never 86 the hero' },
    stack: {
      title: 'Stock without $169/mo software.',
      subtitle: '3 questions at close · order list · supplier days · hero dish safe.',
      items: [
        st('check', '30s check', '3 questions', 'At close', 'stock-check'),
        st('order', 'Order list', 'Tomorrow', 'What to buy', 'order-list'),
        st('hero', 'Hero dish', 'Never 86', 'Mozzarella alert', 'stock-check'),
        st('sup', 'Supplier', 'Right day', 'No mixed orders', 'order-list'),
        st('wa', 'WhatsApp', 'Reminder', '11pm if skipped', 'wa-reply'),
      ],
    },
    signals: {
      title: 'Runouts cost more than software.',
      subtitle: 'One 86 on Friday hurts the whole week.',
      boardLabel: 'STOCK · ALERTS',
      items: [sig('mozzarella low', 90), sig('lampuki delivery tue', 75), sig('wine stock friday', 68), sig('hero dish ingredients', 85)],
      ctaLine: 'Order tomorrow',
    },
    progress: {
      title: 'Mid-service 86 → never again.',
      subtitle: '30 seconds at close.',
      scoreLabel: 'Check streak',
      rankLabel: 'Runouts/mo',
      weeks: [wk(1, 0, 4, 'Runouts weekly'), wk(4, 18, 2, 'Checks habit'), wk(8, 40, 0, 'Order list auto'), wk(12, 60, 0, 'Zero hero 86', '60-day streak')],
    },
    compare: {
      title: 'MarketMan vs 3 questions',
      subtitle: '$169/mo + weeks of setup vs 30 seconds.',
      brainLine: 'Enterprise inventory for a 40-cover venue is theatre. H360 asks three questions.',
      badLabel: 'MARKETMAN', goodLabel: 'H360 STOCK',
      badNote: '$169/mo · setup', goodNote: '30s · 3 questions',
      badMetric: '4 runouts', goodMetric: '0 runouts',
      premiumVisual: 'stock-alert',
    },
  },

  staff: {
    doctrine: 'Another app to download is another shift nobody shows up for.',
    metric: { value: '1 tap', label: 'yes / no — roster in WhatsApp' },
    stack: {
      title: 'Roster where staff already live.',
      subtitle: 'WhatsApp yes/no · sick cover · EVENT staffing · no new app.',
      items: [
        st('roster', 'Roster', 'WhatsApp', 'Saturday shift', 'roster-wa'),
        st('yes', 'YES/NO', 'One tap', 'Confirmed in minutes', 'shift-yes'),
        st('sick', 'Sick cover', 'Broadcast', 'Marco covers', 'wa-reply'),
        st('event', 'Event night', 'Extra server', 'From EVENT calc', 'event-rsvp'),
        st('wa', 'No new app', 'WhatsApp', 'Staff actually reply', 'wa-offer'),
      ],
    },
    signals: {
      title: 'Understaffed Friday costs more than software.',
      subtitle: 'Cover filled in 4 minutes — not 4 hours of calls.',
      boardLabel: 'STAFF · COVER',
      items: [sig('saturday roster', 88), sig('sick cover needed', 92), sig('event extra server', 76), sig('festa week staffing', 70)],
      ctaLine: 'Shift needs',
    },
    progress: {
      title: 'WhatsApp scroll → roster done.',
      subtitle: 'See who confirmed — before service.',
      scoreLabel: 'Shifts filled',
      rankLabel: 'Cover time',
      weeks: [wk(1, 4, 120, 'Group chat chaos'), wk(4, 12, 45, 'YES/NO roster'), wk(8, 24, 12, 'Sick cover fast'), wk(12, 36, 4, 'Roster in minutes', '4 min cover')],
    },
    compare: {
      title: 'Scheduling app vs WhatsApp roster',
      subtitle: '€3/staff/mo · nobody downloads.',
      brainLine: '7Shifts wants adoption. H360 wants one tap in WhatsApp.',
      badLabel: 'SCHEDULING APP', goodLabel: 'H360 STAFF',
      badNote: 'Nobody downloads', goodNote: 'WhatsApp YES',
      badMetric: '4 hrs cover', goodMetric: '4 min',
      premiumVisual: 'staff-whatsapp',
    },
  },

  floorPlan: {
    doctrine: 'The host should never guess which table is free on a Friday.',
    metric: { value: 'live', label: 'green free · red full · yellow turning' },
    stack: {
      title: 'See the floor — seat faster.',
      subtitle: 'Live map · tap to seat · turns · BOOKING sync · no €200/mo enterprise.',
      items: [
        st('map', 'Live map', 'Green/red', 'Every table', 'floor-green'),
        st('seat', 'Tap seat', '4 guests', 'Table 9 · done', 'seat-tap'),
        st('turn', 'Turns', 'Yellow', 'Bill paid · clearing', 'trend'),
        st('book', 'BOOKING sync', 'Reserved', 'No double seat', 'booking-slot'),
        st('host', 'Host calm', 'Friday', 'No guessing', 'owner-dash'),
      ],
    },
    signals: {
      title: 'Faster seating = more covers.',
      subtitle: 'Empty tables waiting on a confused host cost money.',
      boardLabel: 'FLOOR · LIVE',
      items: [sig('table 9 free', 95), sig('party of 6 waiting', 88), sig('turn time 12 min', 72), sig('reserved 20:00', 80)],
      ctaLine: 'Seat next',
    },
    progress: {
      title: 'Host guesswork → live map.',
      subtitle: 'Green · red · yellow — everyone sees the same floor.',
      scoreLabel: 'Seat time',
      rankLabel: 'Turns/night',
      weeks: [wk(1, 8, 3, 'Host guessing'), wk(2, 5, 4, 'Map live'), wk(6, 3, 5, 'BOOKING synced'), wk(12, 2, 6, 'Faster Friday', 'Turns ↑')],
    },
    compare: {
      title: 'Enterprise table software vs live map',
      subtitle: '€200/mo for features a 15-table room does not need.',
      brainLine: 'SevenRooms is enterprise. H360 is green free · red full — one tap.',
      badLabel: 'ENTERPRISE', goodLabel: 'H360 FLOOR',
      badNote: '€200/mo · complex', goodNote: 'Live map · tap',
      badMetric: '8 min wait', goodMetric: '2 min',
      premiumVisual: 'floor-map-live',
    },
  },
};
