// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/h360/BelowHero.tsx": () => import("../components/mockups/h360/BelowHero.tsx"),
  "./components/mockups/h360/DesignSystem.tsx": () => import("../components/mockups/h360/DesignSystem.tsx"),
  "./components/mockups/h360/Hero.tsx": () => import("../components/mockups/h360/Hero.tsx")
};
