/* eslint-disable no-console */
// Generates `public/llms-full.txt` — the full reference document for AI
// answer engines (ChatGPT, Claude, Gemini, Perplexity, Copilot, You.com,
// Brave Leo). Distinct from `public/llms.txt`:
//   - llms.txt is the LIGHT index (URLs + cite-able fact bullets).
//   - llms-full.txt is the FULL reference: every page's TITLE, DESCRIPTION,
//     framework UVP, FEATURES, all FAQs (Q+A), and every llmCitableFact.
//
// Marker-scoped replacement. The autogenerated body sits between:
//   <!-- AUTOGEN:LLMS-FULL:START -->
//   <!-- AUTOGEN:LLMS-FULL:END -->
// Anything OUTSIDE those markers (custom header, manual notes, footer
// signatures) is preserved across runs. Hand-editing INSIDE the markers
// fails the audit — re-run the generator instead.
//
// On first run, if the file is missing, the script writes a complete file
// (header + markers + body + trailing newline). On subsequent runs, only
// the marker-bounded section is replaced.
//
// Usage:
//   npx tsx scripts/generate-llms-full-txt.ts          # regenerate
//   npx tsx scripts/generate-llms-full-txt.ts --check  # parity check, exits 1 on drift

import fs from "node:fs";
import path from "node:path";
import {
  buildLlmsFullFile,
  buildLlmsFullBody,
  applyLlmsFullTransform,
  LLMS_FULL_PATH,
  LLMS_FULL_START,
  LLMS_FULL_END,
} from "../lib/seo/llmsFullBuilder";
import { SERVICE_SCHEMAS } from "../lib/seo/serviceSchemaConfig";
import { PILLAR_SCHEMAS } from "../lib/seo/pillarSchemaConfig";

function main() {
  const checkOnly = process.argv.includes("--check");
  const fullPath = path.join(process.cwd(), LLMS_FULL_PATH);

  if (checkOnly) {
    if (!fs.existsSync(fullPath)) {
      console.error(
        `[generate-llms-full-txt] AUTOGEN parity FAILED — ${LLMS_FULL_PATH} does not exist.\n` +
          "  Run: npx tsx scripts/generate-llms-full-txt.ts",
      );
      process.exit(1);
    }
    const current = fs.readFileSync(fullPath, "utf-8");
    const expected = applyLlmsFullTransform(current);
    if (current !== expected) {
      console.error(
        `[generate-llms-full-txt] AUTOGEN parity FAILED — ${LLMS_FULL_PATH} body is out of date or markers missing.\n` +
          "  Run: npx tsx scripts/generate-llms-full-txt.ts\n" +
          "  Then commit the regenerated file.",
      );
      process.exit(1);
    }
    console.log(
      `AUTOGEN parity ok — ${LLMS_FULL_PATH} body matches generator output (content outside markers preserved)`,
    );
    return;
  }

  let next: string;
  if (!fs.existsSync(fullPath)) {
    // First run — write a complete file with the canonical static header.
    next = buildLlmsFullFile();
  } else {
    // Subsequent runs — preserve everything outside the AUTOGEN markers.
    const current = fs.readFileSync(fullPath, "utf-8");
    next = applyLlmsFullTransform(current);
  }

  fs.writeFileSync(fullPath, next);
  const services = Object.keys(SERVICE_SCHEMAS).length;
  const pillars = Object.keys(PILLAR_SCHEMAS).length;
  const bodyBytes = buildLlmsFullBody().length;
  console.log(
    `wrote ${LLMS_FULL_PATH} — ${pillars} pillars + ${services} services (autogen body: ${bodyBytes} bytes; file: ${next.length} bytes; markers: ${LLMS_FULL_START}/${LLMS_FULL_END})`,
  );
}

main();
