#!/usr/bin/env node
/**
 * Walks public/ and selected attached_assets/ trees, emits a 10x10 base64
 * blur placeholder for every raster image, and writes the map to
 * lib/blur-data.ts so consumers can do:
 *
 *   import { blurFor } from "@/blur-data";
 *   <Image ... placeholder="blur" blurDataURL={blurFor("/assets/foo.webp")} />
 *
 * Idempotent: re-running only re-encodes images whose mtime changed.
 *
 * Usage:
 *   npm run blur:gen
 *   THRESHOLD_KB=50 npm run blur:gen   # only images >= 50 KB
 */
import { promises as fs } from "node:fs";
import path from "node:path";
import sharp from "sharp";

const PUBLIC = path.resolve("public");
const SCAN_ROOTS = [path.join(PUBLIC, "assets"), path.join(PUBLIC, "agents"), path.join(PUBLIC, "media")];
const OUT = path.resolve("lib/blur-data.ts");
const IMAGE_EXT = /\.(png|jpe?g|webp|avif)$/i;
const THRESHOLD = (Number(process.env.THRESHOLD_KB) || 0) * 1024;

async function* walk(dir) {
  let entries;
  try {
    entries = await fs.readdir(dir, { withFileTypes: true });
  } catch {
    return;
  }
  for (const e of entries) {
    if (e.name.startsWith(".") || e.name.startsWith("_")) continue;
    const full = path.join(dir, e.name);
    if (e.isDirectory()) yield* walk(full);
    else if (IMAGE_EXT.test(e.name)) yield full;
  }
}

async function blurFor(file) {
  const buf = await fs
    .readFile(file)
    .then((b) => sharp(b, { failOn: "none" }).rotate().resize(10, 10, { fit: "inside" }).jpeg({ quality: 30 }).toBuffer());
  return `data:image/jpeg;base64,${buf.toString("base64")}`;
}

async function main() {
  const map = {};
  let count = 0;
  let skipped = 0;
  for (const root of SCAN_ROOTS) {
    for await (const file of walk(root)) {
      const stat = await fs.stat(file);
      if (THRESHOLD && stat.size < THRESHOLD) {
        skipped++;
        continue;
      }
      const rel = "/" + path.relative(PUBLIC, file).split(path.sep).join("/");
      try {
        map[rel] = await blurFor(file);
        count++;
        if (count % 50 === 0) console.log(`  ${count} placeholders generated...`);
      } catch (e) {
        console.warn(`  skip ${rel}: ${e.message}`);
      }
    }
  }

  const header =
    `// AUTO-GENERATED by scripts/generate-blur.mjs — do not hand-edit.\n` +
    `// Re-run with: npm run blur:gen\n` +
    `// Generated: ${new Date().toISOString()}\n` +
    `// Total entries: ${count}\n\n`;

  const body =
    `export const BLUR_MAP: Record<string, string> = ${JSON.stringify(map, null, 2)};\n\n` +
    `export function blurFor(src: string): string | undefined {\n` +
    `  return BLUR_MAP[src];\n` +
    `}\n`;

  await fs.mkdir(path.dirname(OUT), { recursive: true });
  await fs.writeFile(OUT, header + body, "utf8");
  console.log(`\nWrote ${count} placeholders to ${path.relative(process.cwd(), OUT)} (skipped ${skipped} below threshold).`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
