// AUTO-GENERATED by .local/scripts/build-image-registry.mjs — do not edit by hand.
// Source of truth for all 38 user-supplied images. Re-run the script to refresh.

export type ImageCategory =
  | "Real Estate"
  | "Healthcare"
  | "Hospitality"
  | "iGaming"
  | "Organic Acquisition"
  | "Testimonials"
  | "Creative AI Powerhouse"
  | "Hidden AI Features"
  | "Future of Island"
  | "CTAs"
  | "Business Diagnostics"
  | "Operations 360"
  | "Hiring Engine"
  | "Misc";

export interface RegistryImage {
  id: string;
  originalPath: string;
  seoFilename: string;
  altText: string;
  caption: string;
  dimensions: { width: number; height: number };
  category: ImageCategory;
  assignedTo: string[];
}

export const IMAGE_REGISTRY: readonly RegistryImage[] = [
  {
    "id": "img-001",
    "originalPath": "attached_assets/hf_20260420_104042_398e075c-5536-4b20-820c-844b0e6be0ed_1777849689043.png",
    "seoFilename": "death-by-missed-leads-sliema-real-estate-malta",
    "altText": "Sliema real estate agent buried in missed leads after-hours",
    "caption": "Real estate Malta — missed-leads pain visualised.",
    "dimensions": {
      "width": 2048,
      "height": 2048
    },
    "category": "Real Estate",
    "assignedTo": [
      "/industries/real-estate",
      "/malta/sliema/real-estate"
    ]
  },
  {
    "id": "img-002",
    "originalPath": "attached_assets/hf_20260420_104245_790561aa-c963-4bc2-a8ea-c979551e497d_1777849689043.png",
    "seoFilename": "real-estate-ai-receptionist-malta-property-agency",
    "altText": "AI receptionist taking property enquiries for a Malta real estate agency at night",
    "caption": "AI never sleeps — bookings while you do.",
    "dimensions": {
      "width": 2048,
      "height": 2048
    },
    "category": "Real Estate",
    "assignedTo": [
      "/industries/real-estate",
      "/ai-agents/ai-appointment-booker"
    ]
  },
  {
    "id": "img-003",
    "originalPath": "attached_assets/hf_20260420_104349_586e06ee-488a-4e5f-a60c-68de266bc921_1777849689043.png",
    "seoFilename": "property-listing-funnel-automation-malta",
    "altText": "Property listing funnel automation flow for Malta real estate brokers",
    "caption": "From listing to viewing in three automated steps.",
    "dimensions": {
      "width": 2048,
      "height": 2048
    },
    "category": "Real Estate",
    "assignedTo": [
      "/industries/real-estate",
      "/services/funnel-automation"
    ]
  },
  {
    "id": "img-004",
    "originalPath": "attached_assets/hf_20260420_104453_5a0e2d7c-d9d4-4d73-95a0-501f663a9c73_1777849689043.png",
    "seoFilename": "real-estate-malta-conversion-dashboard",
    "altText": "Conversion dashboard for a Sliema real estate office showing booked viewings",
    "caption": "Track every viewing booked, by source.",
    "dimensions": {
      "width": 2048,
      "height": 2048
    },
    "category": "Real Estate",
    "assignedTo": [
      "/industries/real-estate"
    ]
  },
  {
    "id": "img-005",
    "originalPath": "attached_assets/hf_20260420_104711_29f21c53-ba1c-44c3-b15b-d4c09ad0846f_1777849689042.png",
    "seoFilename": "healthcare-clinic-ai-booking-malta",
    "altText": "Malta private clinic patient booking on a smartphone with AI confirmation",
    "caption": "Private clinics in Malta booked while reception sleeps.",
    "dimensions": {
      "width": 2048,
      "height": 2048
    },
    "category": "Healthcare",
    "assignedTo": [
      "/industries/healthcare-clinics",
      "/ai-agents/ai-appointment-booker"
    ]
  },
  {
    "id": "img-006",
    "originalPath": "attached_assets/hf_20260420_105621_ca372d08-65bd-489e-94b8-64550a070e23_1777849689042.png",
    "seoFilename": "doctor-patient-followup-automation-malta",
    "altText": "Automated patient follow-up message sequence for a Malta doctor",
    "caption": "Patient follow-ups that never get forgotten.",
    "dimensions": {
      "width": 2752,
      "height": 1536
    },
    "category": "Healthcare",
    "assignedTo": [
      "/industries/healthcare-clinics"
    ]
  },
  {
    "id": "img-007",
    "originalPath": "attached_assets/hf_20260420_110118_7550d988-bf93-45c0-b657-8533bafeeba7_1777849689042.png",
    "seoFilename": "private-clinic-malta-revenue-recovery",
    "altText": "Private clinic in Malta recovering missed-appointment revenue with AI",
    "caption": "Reclaim revenue lost to missed appointments.",
    "dimensions": {
      "width": 2752,
      "height": 1536
    },
    "category": "Healthcare",
    "assignedTo": [
      "/industries/healthcare-clinics"
    ]
  },
  {
    "id": "img-008",
    "originalPath": "attached_assets/hf_20260420_110134_9e1d7c1d-85b3-4676-b715-62b2b125577e_1777849689042.png",
    "seoFilename": "hospitality-malta-restaurant-ai-bookings",
    "altText": "Restaurant in Valletta receiving AI-handled reservations on tablet",
    "caption": "Tables filled while the kitchen runs.",
    "dimensions": {
      "width": 2752,
      "height": 1536
    },
    "category": "Hospitality",
    "assignedTo": [
      "/industries/restaurants-cafes",
      "/industries/hotels-hospitality"
    ]
  },
  {
    "id": "img-009",
    "originalPath": "attached_assets/hf_20260420_110400_f275b238-63f3-432e-9bf6-8c751eff68cf_1777849689041.png",
    "seoFilename": "hotel-malta-ai-concierge-bookings",
    "altText": "Boutique Malta hotel AI concierge handling guest enquiries 24/7",
    "caption": "Boutique hotels — concierge that never clocks out.",
    "dimensions": {
      "width": 2752,
      "height": 1536
    },
    "category": "Hospitality",
    "assignedTo": [
      "/industries/hotels-hospitality"
    ]
  },
  {
    "id": "img-010",
    "originalPath": "attached_assets/hf_20260420_110651_c79565e9-5cf0-4a29-a4d8-966374bda9db_1777849689041.png",
    "seoFilename": "igaming-malta-player-support-ai",
    "altText": "iGaming operator in Malta routing player support tickets through an AI workflow",
    "caption": "iGaming player support, triaged in seconds.",
    "dimensions": {
      "width": 2048,
      "height": 2048
    },
    "category": "iGaming",
    "assignedTo": [
      "/industries/igaming-betting"
    ]
  },
  {
    "id": "img-011",
    "originalPath": "attached_assets/hf_20260420_065011_d9310ea4-689e-4251-a67b-14bfb035b894_1777849804956.png",
    "seoFilename": "organic-acquisition-engine-malta",
    "altText": "Organic acquisition engine diagram for a Malta marketing agency",
    "caption": "Compounding traffic, not paid sugar-rushes.",
    "dimensions": {
      "width": 1856,
      "height": 2304
    },
    "category": "Organic Acquisition",
    "assignedTo": [
      "/",
      "/services/seo-services",
      "/services/content-marketing"
    ]
  },
  {
    "id": "img-012",
    "originalPath": "attached_assets/hf_20260420_071421_fb6580db-57d8-4083-9a1b-3cdd11892575_1777849804956.png",
    "seoFilename": "seo-content-flywheel-malta",
    "altText": "SEO + content flywheel illustration for Maltese SMBs",
    "caption": "Search + content — one compounding flywheel.",
    "dimensions": {
      "width": 2752,
      "height": 1536
    },
    "category": "Organic Acquisition",
    "assignedTo": [
      "/services/seo-services"
    ]
  },
  {
    "id": "img-013",
    "originalPath": "attached_assets/hf_20260420_071839_c82a0cfc-19d7-4948-8150-0c3221565cf8_1777849804956.png",
    "seoFilename": "topical-authority-pillar-cluster-map",
    "altText": "Pillar-and-cluster topical authority map for a Malta service business",
    "caption": "Own the topic, not just the keyword.",
    "dimensions": {
      "width": 1856,
      "height": 2304
    },
    "category": "Organic Acquisition",
    "assignedTo": [
      "/services/seo-services",
      "/services/content-marketing"
    ]
  },
  {
    "id": "img-014",
    "originalPath": "attached_assets/hf_20260420_072158_aa96d60e-4efd-4477-a57e-57184b99dd3f_1777849804956.png",
    "seoFilename": "answer-engine-optimisation-aeo-malta",
    "altText": "Answer Engine Optimisation (AEO) workflow for ranking in AI search results",
    "caption": "Be the answer AI search hands back.",
    "dimensions": {
      "width": 2752,
      "height": 1536
    },
    "category": "Organic Acquisition",
    "assignedTo": [
      "/services/seo-services",
      "/aeo"
    ]
  },
  {
    "id": "img-015",
    "originalPath": "attached_assets/Business_development_manager_1768204442837.png",
    "seoFilename": "testimonial-business-development-manager-malta",
    "altText": "Business development manager headshot — Malta client testimonial",
    "caption": "“Bookings tripled in the first six weeks.”",
    "dimensions": {
      "width": 2000,
      "height": 2000
    },
    "category": "Testimonials",
    "assignedTo": [
      "/",
      "/case-studies",
      "/why-us"
    ]
  },
  {
    "id": "img-016",
    "originalPath": "attached_assets/Customer_support_specalist_1768204442837.png",
    "seoFilename": "testimonial-customer-support-specialist-malta",
    "altText": "Customer support specialist headshot — Malta client testimonial",
    "caption": "“Tickets resolved 5× faster with AI triage.”",
    "dimensions": {
      "width": 2000,
      "height": 2000
    },
    "category": "Testimonials",
    "assignedTo": [
      "/",
      "/case-studies",
      "/ai-agents/ai-support-specialist"
    ]
  },
  {
    "id": "img-017",
    "originalPath": "attached_assets/sales_manager_1768204442838.png",
    "seoFilename": "testimonial-sales-manager-malta",
    "altText": "Sales manager headshot — Malta client testimonial",
    "caption": "“Pipeline doubled, ad spend halved.”",
    "dimensions": {
      "width": 3000,
      "height": 3000
    },
    "category": "Testimonials",
    "assignedTo": [
      "/",
      "/case-studies",
      "/ai-agents/ai-sdr-agent"
    ]
  },
  {
    "id": "img-018",
    "originalPath": "attached_assets/hf_20260420_073322_c1ddc88f-d246-438e-a7e2-11a9f24fc50a_1777849804955.png",
    "seoFilename": "creative-ai-powerhouse-studio-malta",
    "altText": "Creative AI studio producing brand-matched imagery for a Malta agency",
    "caption": "Brand-distinct creative, generated at agency scale.",
    "dimensions": {
      "width": 2752,
      "height": 1536
    },
    "category": "Creative AI Powerhouse",
    "assignedTo": [
      "/creative",
      "/services/branding"
    ]
  },
  {
    "id": "img-019",
    "originalPath": "attached_assets/hf_20260420_074625_be48d049-bbde-4890-b6f6-4e3b0e8c9303_(1)_1777849804955.png",
    "seoFilename": "ai-video-production-pipeline-malta",
    "altText": "AI-assisted video production pipeline for short-form social",
    "caption": "Story-boarded shots, generated overnight.",
    "dimensions": {
      "width": 1856,
      "height": 2304
    },
    "category": "Creative AI Powerhouse",
    "assignedTo": [
      "/creative",
      "/services/video-production"
    ]
  },
  {
    "id": "img-020",
    "originalPath": "attached_assets/hf_20260420_074920_40fbb419-0f59-45b8-8848-75a54702595f_1777849804955.png",
    "seoFilename": "ad-creative-variants-generator-malta",
    "altText": "Dozens of ad creative variants generated from a single brand brief",
    "caption": "100 ad variants from one brief.",
    "dimensions": {
      "width": 2752,
      "height": 1536
    },
    "category": "Creative AI Powerhouse",
    "assignedTo": [
      "/creative",
      "/services/paid-advertising"
    ]
  },
  {
    "id": "img-021",
    "originalPath": "attached_assets/hf_20260420_080536_fc86c907-ce10-46b8-89bb-00de441f26ad_1777849804954.png",
    "seoFilename": "hidden-ai-features-control-room-malta",
    "altText": "Operator control room view of OARC's hidden AI feature stack",
    "caption": "What runs behind the curtain, surfaced.",
    "dimensions": {
      "width": 1856,
      "height": 2304
    },
    "category": "Hidden AI Features",
    "assignedTo": [
      "/ai-agents",
      "/solutions"
    ]
  },
  {
    "id": "img-022",
    "originalPath": "attached_assets/hf_20260420_082039_d1873fdc-a327-40df-8799-f526876b472d_1777849804954.png",
    "seoFilename": "ai-knowledge-base-grounding-malta",
    "altText": "AI agent grounded on a private company knowledge base",
    "caption": "Agents that actually know your business.",
    "dimensions": {
      "width": 1856,
      "height": 2304
    },
    "category": "Hidden AI Features",
    "assignedTo": [
      "/ai-agents",
      "/ai-consulting"
    ]
  },
  {
    "id": "img-023",
    "originalPath": "attached_assets/hf_20260420_090501_ab407b9d-6ce2-45cc-bc91-2f74476e628a_1777849689046.png",
    "seoFilename": "agent-handover-to-human-malta",
    "altText": "Seamless handover from AI agent to human team member",
    "caption": "AI handles 80% — humans get the 20% that matters.",
    "dimensions": {
      "width": 1856,
      "height": 2304
    },
    "category": "Hidden AI Features",
    "assignedTo": [
      "/ai-agents"
    ]
  },
  {
    "id": "img-024",
    "originalPath": "attached_assets/hf_20260420_092531_eb2d7176-d6ae-4c1c-b0c4-e9d71f9cfe0b_1777849689045.png",
    "seoFilename": "ai-agent-multichannel-orchestration",
    "altText": "AI agent orchestrating WhatsApp, email and web chat in one inbox",
    "caption": "WhatsApp, email, web — one agent, one inbox.",
    "dimensions": {
      "width": 1856,
      "height": 2304
    },
    "category": "Hidden AI Features",
    "assignedTo": [
      "/ai-agents",
      "/solutions"
    ]
  },
  {
    "id": "img-025",
    "originalPath": "attached_assets/hf_20260420_092624_29a951de-b62e-476c-898c-d9d468b1c638_(1)_1777849689045.png",
    "seoFilename": "future-of-island-malta-ai-economy",
    "altText": "Aerial view of Malta with AI-driven business overlay — future of the island economy",
    "caption": "Malta's next decade runs on AI.",
    "dimensions": {
      "width": 1856,
      "height": 2304
    },
    "category": "Future of Island",
    "assignedTo": [
      "/",
      "/about",
      "/why-us"
    ]
  },
  {
    "id": "img-026",
    "originalPath": "attached_assets/hf_20260420_092624_29a951de-b62e-476c-898c-d9d468b1c638_1777902275175.png",
    "seoFilename": "malta-business-ai-transformation-2026",
    "altText": "Malta SMB business owner adopting AI tooling — 2026 transformation",
    "caption": "Maltese SMBs leapfrogging to AI-first ops.",
    "dimensions": {
      "width": 1856,
      "height": 2304
    },
    "category": "Future of Island",
    "assignedTo": [
      "/about",
      "/ai-consulting"
    ]
  },
  {
    "id": "img-027",
    "originalPath": "attached_assets/hf_20260420_094949_ad959914-4e7a-46be-af70-29cfad5dbbca_(1)_1777849689044.png",
    "seoFilename": "cta-book-strategy-call-oarc-malta",
    "altText": "Book a strategy call CTA banner for OARC Digital Malta",
    "caption": "Book a 30-min strategy call.",
    "dimensions": {
      "width": 1856,
      "height": 2304
    },
    "category": "CTAs",
    "assignedTo": [
      "/contact",
      "/",
      "/pricing"
    ]
  },
  {
    "id": "img-028",
    "originalPath": "attached_assets/hf_20260419_190835_5d66a129-54d0-4be1-9e07-0a0f88c80446_1777849804957.png",
    "seoFilename": "cta-free-business-diagnostic-malta",
    "altText": "Free business diagnostic CTA banner — Malta SMBs",
    "caption": "Get a free 7-point diagnostic.",
    "dimensions": {
      "width": 928,
      "height": 1152
    },
    "category": "CTAs",
    "assignedTo": [
      "/diagnostics",
      "/contact"
    ]
  },
  {
    "id": "img-029",
    "originalPath": "attached_assets/OPERATIONS_360._We_SAVE_YOU_TIME_&_MONEY_From_Chaos_to_Control_1777849689044.png",
    "seoFilename": "operations-360-from-chaos-to-control-malta",
    "altText": "OARC Operations 360 — from chaos to control framework for Malta SMBs",
    "caption": "From chaos to control — Operations 360.",
    "dimensions": {
      "width": 5153,
      "height": 6400
    },
    "category": "Business Diagnostics",
    "assignedTo": [
      "/diagnostics",
      "/automation"
    ]
  },
  {
    "id": "img-030",
    "originalPath": "attached_assets/OPERATIONS_360._We_SAVE_YOU_TIME_&_MONEY_From_Chaos_to_Control_1777902275174.png",
    "seoFilename": "operations-360-time-money-savings-framework",
    "altText": "Operations 360 framework showing time and money saved across functions",
    "caption": "Hours and Euros, recovered every month.",
    "dimensions": {
      "width": 5153,
      "height": 6400
    },
    "category": "Operations 360",
    "assignedTo": [
      "/automation",
      "/services/marketing-automation-suite"
    ]
  },
  {
    "id": "img-031",
    "originalPath": "attached_assets/HIRING_A_MARKETING_AG_1777849804957.png",
    "seoFilename": "hiring-marketing-agency-vs-ai-employees-malta",
    "altText": "Hiring a marketing agency vs hiring AI employees — comparison for Malta SMBs",
    "caption": "Agency vs AI employees — the real maths.",
    "dimensions": {
      "width": 5153,
      "height": 6400
    },
    "category": "Hiring Engine",
    "assignedTo": [
      "/hire-ai-employees",
      "/why-us",
      "/pricing"
    ]
  },
  {
    "id": "img-032",
    "originalPath": "attached_assets/Best-Large-Social-Agency_1761760464709.webp",
    "seoFilename": "best-large-social-media-agency-malta-award",
    "altText": "Best large social media agency Malta — award badge",
    "caption": "Recognised among Malta's best social agencies.",
    "dimensions": {
      "width": 1200,
      "height": 1200
    },
    "category": "Misc",
    "assignedTo": [
      "/about",
      "/why-us",
      "/services/social-media-creative-management"
    ]
  },
  {
    "id": "img-033",
    "originalPath": "attached_assets/creative media studio_1764278639970.jpg",
    "seoFilename": "creative-media-studio-malta-content-production",
    "altText": "OARC creative media studio in Malta producing branded content",
    "caption": "In-house studio, agency-grade output.",
    "dimensions": {
      "width": 1024,
      "height": 1024
    },
    "category": "Misc",
    "assignedTo": [
      "/creative",
      "/our-work"
    ]
  },
  {
    "id": "img-034",
    "originalPath": "attached_assets/AI product solutionssss_1764278639969.webp",
    "seoFilename": "ai-product-solutions-malta-revenue-stack",
    "altText": "OARC AI product solutions stack for Malta revenue teams",
    "caption": "Your full revenue stack — productised.",
    "dimensions": {
      "width": 1200,
      "height": 400
    },
    "category": "Misc",
    "assignedTo": [
      "/solutions",
      "/ai-agents"
    ]
  },
  {
    "id": "img-035",
    "originalPath": "attached_assets/workflow automations_1764278639971.png",
    "seoFilename": "workflow-automations-malta-revenue-operations",
    "altText": "Workflow automation diagram connecting CRM, calendar, WhatsApp and email for Malta SMBs",
    "caption": "Tools you already pay for, finally talking.",
    "dimensions": {
      "width": 1273,
      "height": 1082
    },
    "category": "Misc",
    "assignedTo": [
      "/automation",
      "/services/marketing-automation-suite"
    ]
  },
  {
    "id": "img-036",
    "originalPath": "attached_assets/bookings_1768204442836.png",
    "seoFilename": "ai-bookings-dashboard-malta",
    "altText": "AI bookings dashboard for a Malta service business",
    "caption": "Every booking, every channel, one view.",
    "dimensions": {
      "width": 2000,
      "height": 2000
    },
    "category": "Misc",
    "assignedTo": [
      "/ai-agents/ai-appointment-booker"
    ]
  },
  {
    "id": "img-037",
    "originalPath": "attached_assets/Follow_up_1768204442837.png",
    "seoFilename": "ai-follow-up-automation-malta-leads",
    "altText": "AI lead follow-up automation across SMS, email and WhatsApp",
    "caption": "Follow-ups, on autopilot.",
    "dimensions": {
      "width": 3000,
      "height": 3000
    },
    "category": "Misc",
    "assignedTo": [
      "/ai-agents/ai-sdr-agent",
      "/services/marketing-automation-suite"
    ]
  },
  {
    "id": "img-038",
    "originalPath": "attached_assets/Sales_1768204442839.png",
    "seoFilename": "ai-sales-pipeline-dashboard-malta",
    "altText": "AI sales pipeline dashboard for a Malta B2B team",
    "caption": "Pipeline visibility your reps actually use.",
    "dimensions": {
      "width": 2000,
      "height": 2000
    },
    "category": "Misc",
    "assignedTo": [
      "/ai-agents/ai-sdr-agent"
    ]
  }
] as const;

export function getImage(id: string): RegistryImage | undefined {
  return IMAGE_REGISTRY.find((i) => i.id === id);
}

export function getImagesByCategory(c: ImageCategory): RegistryImage[] {
  return IMAGE_REGISTRY.filter((i) => i.category === c);
}

export function getImagesForRoute(route: string): RegistryImage[] {
  return IMAGE_REGISTRY.filter((i) => i.assignedTo.includes(route));
}

export function publicSrc(img: RegistryImage, ext: "avif" | "webp" | "jpg" = "avif"): string {
  return `/images/registry/${img.seoFilename}.${ext}`;
}
